### ISSUE TITLE
Import Error in map() quiz

### ISSUE THREAD

**Issue by ghoshabhi** [udacity/reactnd-issues#1]
Here's the link to the quiz: 

https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd

When I "Test Run" my solution, I get an error saying:

"Import Error: No module named studentMain", although quiz submissions seems to work fine

Chrome Version: Version 58.0.3029.110 (64-bit)

**Comment by kellim** [comment]
I also got this error when I ran "Test Run" on my solution:
<code>Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_dpeqldbgci/main.py", line 2, in <module>
    import studentMain
ImportError: No module named studentMain</code>

Then after I clicked Submit, it said "Try Again" and "Thank you for your submission!" 
However, when I ran the code from the quiz in the browser, it looked like I got the correct result. I would post my code here but not sure if you want quiz answers posted on this repo.

**Comment by richardkalehoff** [comment]
This has been fixed!
