### ISSUE TITLE
Lesson 1.3 Declarative Code Recap - remove "With"

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#10]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/dad1ab97-c06e-43fa-a29a-827a9518812e

Under the Declarative Code Recap heading, it says "With imperative code that's written instructs JavaScript on how it should perform each step. With declarative code, we tell JavaScript what we want done and let JavaScript take care of performing the steps." 

It will sound better if the "With" is removed from the first sentence so it reads: "Imperative code that's written instructs JavaScript on how it should perform each step."

**Comment by hbkwong** [comment]
Good to go! Thanks for catching that.
