### ISSUE TITLE
Lesson 3 — Code Inconsistency in Examples

### ISSUE THREAD

**Issue by jenniesyip** [udacity/reactnd-issues#101]
Throughout the beginning of the course, components are created through the syntax `class ComponentName extends Component`, then in Lesson 3, Part 3, all of a sudden `class ComponentName extends React.Component` appears without an introduction on what the difference is, and is also mixed with the prior form. 

I think we need to show that in order to do `class ComponentName extends React.Component` then we need to show that `import React, { Component } from 'react'` will change to `import React from 'react'`

![reactnd-class-extends](https://user-images.githubusercontent.com/1864971/28999378-8e15bd92-79f9-11e7-8841-7852e0b478d4.png)

**Comment by hbkwong** [comment]
Good call, @jenniesyip. Both are used liberally through the course, so some explanation that they're functionally the same should clear up any confusion. That is, components can be defined as a JavaScript class that inherits from React.Component, but the import will obviously change. I'll find a good spot for it and put it together.

**Comment by hbkwong** [comment]
Ready to rock. Added a disclaimer to the area in which we first introduce Components.

https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/d9831309-352a-4e04-83f3-ac3e4e8cac76?contentVersion=1.0.0&contentLocale=en-us

**Comment by jenniesyip** [comment]
![image](https://user-images.githubusercontent.com/1864971/29049672-31e6ed04-7b8c-11e7-82a0-dc6d72a2c86b.png)

LGTM! :) Thanks!

**Comment by hbkwong** [comment]
👍
