### ISSUE TITLE
The Store: A Single Source of Truth: typo in explanation for question?

### ISSUE THREAD

**Issue by mdmss37** [udacity/reactnd-issues#103]
When entering answer, explanation to the third question is as below, but I thought below "React" should be "Redux".

"React" does implement a single state tree. With all of the data in one location and maintained through one interface, it makes debugging and working with data more straightforward.

**Comment by hbkwong** [comment]
Hi mdmss37, good catch! It's been updated. Thanks for reaching out on this one.
