### ISSUE TITLE
Redux 1.5 Link Issue

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#104]
Under the Further Research section at the bottom of the page, the second link "What is Functional Programming?" is showing markdown formatting instead of just the link. It looks like there's a space between ] and ( that is causing the issue.

https://classroom.udacity.com/nanodegrees/nd019beta/parts/058216cd-7eec-481c-8504-976ec423c466/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/b17ccf2f-3f89-4c38-91ae-bd67c083bba2/concepts/154f1d72-c267-4072-bab9-30a92bedcf63#

**Comment by hbkwong** [comment]
Fixed! Thanks for catching that one Kelli
