### ISSUE TITLE
Redux 1.6 Just Reduce Quiz

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#105]
I think the quiz instructions should mention you need to do a `console.log` statement with the answer or else you'll get a message that says "Your code displayed no output"

https://classroom.udacity.com/nanodegrees/nd019beta/parts/058216cd-7eec-481c-8504-976ec423c466/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/b17ccf2f-3f89-4c38-91ae-bd67c083bba2/concepts/06b63ac2-a6bf-4aaf-9122-78cc99fc7918#

**Comment by kellim** [comment]
It looks like you only get that when you do a "Test Run" not submit the quiz, so maybe it doesn't matter.

**Comment by hbkwong** [comment]
Hey Kelli, thanks for the heads up. I'll keep it in mind if I see further feedback on this, since this would apply to all programming quizzes (inside and outside of the Redux course). "Test Run" is really just runs the code in the editor.

Hope you're having a great weekend! 👍
