### ISSUE TITLE
Redux 1.6 Combining Filter and Reduce Quiz

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#106]
It would be a better experience if you didn't have to scroll over using the scrollbar on lines 4 and 5 in order to read instructions.

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/058216cd-7eec-481c-8504-976ec423c466/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/b17ccf2f-3f89-4c38-91ae-bd67c083bba2/concepts/06b63ac2-a6bf-4aaf-9122-78cc99fc7918#

**Comment by hbkwong** [comment]
Fixed! I'm not a fan or horizontal scrolling either. Thanks again Kelli!
