### ISSUE TITLE
Redux 2.4:

### ISSUE THREAD

**Issue by asparr** [udacity/reactnd-issues#108]
Redux 2,4:

".dispatch()
store.dispatch(action) takes in an action object and will call then invokes the reducer function passing it the current store and the action which was dispatched. "

I also feel like there wasn't much of a discussion on dispatch/subscribe? not sure how much these will figure in later on, but I think it would have been nice to have a quick example

**Comment by hbkwong** [comment]
Fixed the phrasing of that excerpt to read more clearly:  _`store.dispatch(action)` takes in an action object and will call the reducer function, passing it the current state and the action which was dispatched._

Tyler shows examples of using `subscribe()` in following screencasts, but `subscribe()`'s role is downplayed. Later lessons go into detail on `connect()`, which is the optimized and preferred way of producing container components.

Added an example for `dispatch()` in this concept. Good to go!
