### ISSUE TITLE
Redux - broken markdown link

### ISSUE THREAD

**Issue by Mackiovello** [udacity/reactnd-issues#109]
In the [middleware lesson](https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/84a3ef1e-8dc3-4608-8547-36c14c79e1f6/concepts/1b28036b-e9b2-4a8a-9f92-b613f5542f90) there's a broken link. It says 
> `[redux-logger(https://www.npmjs.com/package/redux-logger)`

when it should be
> `[redux-logger](https://www.npmjs.com/package/redux-logger)`

**Comment by hbkwong** [comment]
Done! Thank you for checking in on this one. Hope you found the link useful! @Mackiovello
