### ISSUE TITLE
Lesson 1.4 - missing the word "frameworks"

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#11]
The first sentence on the page says "Front-end like Angular and Ember make use of two-way data bindings."

It sounds like it is missing the word framework and would sound better as 
"Front-end frameworks like Angular and Ember make use of two-way data bindings."

**Comment by kellim** [comment]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/03b53d7e-ae83-4846-bff3-bc4015cd8d76

**Comment by richardkalehoff** [comment]
Fixed! Thanks!
