### ISSUE TITLE
redux/lesson5/segment4 quiz

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#111]
I have no clear suggestion on this one, but would like to relay that I received two tickets on LH about the quiz being hard. I suggested the student to consider the following: 1. A function has to be returned before it can be invoked 2. What initiates the whole chain of events?  Those seemed to help in at least one case. (The other already left)

**Comment by hbkwong** [comment]
Hey @zhangtreefish, the prompt has been updated! I saw feedback over this through the weekend too, so the fix is good to go. Thanks for chiming in!
