### ISSUE TITLE
Redux: Lesson 5: Quiz 4: Thunks

### ISSUE THREAD

**Issue by evankline** [udacity/reactnd-issues#113]
The order accepted as the solution seems incorrect. 

1. API request occurs, 
2. Action creator returns a function
3. Thunk invokes function with dispatch, 
4. API request is resolved
5. Action is dispatched.

Whereas it would suggest from the code in the quiz that the action creator first returns a function.

**Comment by hbkwong** [comment]
Hi @evankline, thank you for reaching out! The prompt has been updated. The action creator returns an entire function that carries out the said events. Feel free to refresh and let me know how things go!
