### ISSUE TITLE
redux/lesson4/segment4 on edamam API

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#114]
This may not be a real bug, but I am running into a curious problem: I can see API responded with data from DevTool response body tab, but console logs ```Uncaught (in promise) SyntaxError: Unexpected end of input
    at api.js:21``` error

**Comment by zhangtreefish** [comment]
this is api.js:
```// const API_ID = 'blah'
// const APP_KEY =  'blah2'
const headers = {

   'mode': 'no-cors',
    'header': {
      'Access-Control-Allow-Origin':'*',
  }
}

export function fetchRecipes (food = '') {
  food = food.trim()

  return fetch(`https://api.edamam.com/search?q=${food}&app_id=${API_ID}&app_key=${APP_KEY}`,  headers)
    .then(res => {
    	console.log('res', JSON.stringify(res))
    	return res.json()})
    .then(({ hits }) => hits.map(({ recipe }) => recipe))
}```

**Comment by zhangtreefish** [comment]
![redux_lesson4_segment4_edamam.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed683e7b5e44130052ea0a/125516c66e82c728ace21e0d46fa919e369abca58afaac4caa09cf872c412a762710f7147581e225be4f394d4d1f0cf31b0d0c00eef39b2eafb23470df0d59b9d83b5d72c43d11fabf8b1abd04be29995397f4edd4189fb5646fb2c99d452c1d041288fa5d37a29948cb5cf749e24b47e9.jpg)

**Comment by zhangtreefish** [comment]
![redux_lesson4_segment4_edamam_Res_body.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed683e7b5e44130052ea0a/125516c66e82c728ace21e0d46fa919e369abca58afaac4caa09cf872c412a762710f7147581e225be4f44330a1c21fe1e0c1656e0ebc969f9ec6923ce4e01ffd4645b7cc66840feec8b49bd07b8208b1982bfb98849c4e12f39f5c9de116a415841c3aa1f27aa8b48c952f74ee14f57a4103362e272357f55d9.jpg)

**Comment by zhangtreefish** [comment]
Never mind, my 'headers' was missing {}, after adding that, it works! ``` return fetch(`https://api.edamam.com/search?q=${food}&app_id=${API_ID}&app_key=${APP_KEY}`,  {headers})```

**Comment by hbkwong** [comment]
@zhangtreefish Great! I'll keep an eye out in the Slack for anyone that may have run into this too

**Comment by zhangtreefish** [comment]
I have gotten two LH tickets on this (not sure if it is from the same student).

**Comment by zhangtreefish** [comment]
It turns out  api.js works as is without the need for {headers}.
