### ISSUE TITLE
assigning a function to store

### ISSUE THREAD

**Issue by rscharfer** [udacity/reactnd-issues#115]
Lesson 2: Create a redux store, .dispatch()

Rather than assigning the store variable with the return value of createStore(), the variable is assigned with a function.

**Comment by rscharfer** [comment]
![functionAssignedToStore.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5976d7d6322ccf001a1cd5bb/125516c66e82c728ace21e0d46ee819420968aa681c8ac50ad5afe912d7228403d0bb12e32c9a138ad4d71040c1b5ca6535d5640f4f9dc7af4e23526885a09edd13b587dc33f14a8b19003ad43eb7edf10d8eff6df0ed2e22f26e6818e4a3e1c071981f7583ca79848da15.PNG)

**Comment by rscharfer** [comment]
later .dispatch() is called on "store" which wouldn't work because store is a function at this point and would not have this method on it.

**Comment by hbkwong** [comment]
Hi @rscharfer, the typo has been corrected. Thanks for checking in on this one!
