### ISSUE TITLE
Typo: favIceCream  array is named iceCreamStats

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/reactnd-issues#116]
3. React & Redux => Lesson 1: Why Redux? => 6.Array's .reduce() Method

Link: https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/b17ccf2f-3f89-4c38-91ae-bd67c083bba2/concepts/06b63ac2-a6bf-4aaf-9122-78cc99fc7918

The description says "consider the following favIceCream array" but the example has an array with name "iceCreamStats".

**Comment by hbkwong** [comment]
Good catch! Fixed @ravikumarseth
