### ISSUE TITLE
redux/lesson1/segment6

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#117]
'filter the musicData array down to just the albums that a combined   artist + name length of 25 characters'  is not clear by itself, although the example clarifies the requirement. How about "...down to just the albums with a maximal combined 'artist' and 'name' string length of 25 characters'"?

**Comment by hbkwong** [comment]
Fixed! That and the example should be clear now. No tests have been altered otherwise. Thank you as always @zhangtreefish !
