### ISSUE TITLE
redux/lesson1/segment6 answer

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#118]
If the answer is derived by first doing a filter and then do a reduce on the result of the filter, the grader gives an error 'What Went Wrong
- Your code doesn't appear to call .reduce() on the array returned from .filter()'. If done in a chained fashion, it lets pass.

**Comment by zhangtreefish** [comment]
![redux_lesson1_seg6_combinedFilterReduce.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed683e7b5e44130052ea0a/125516c66e82c728ace21e0d46fa919e369abca58afaac4caa0ccf872c41714c2a0bae29798be62c994b77150a1d2cf9151d0c11eee59b6be4e96625d91819e7c3685670ce3d44fdead616e903bc228b4fd3b1b58f4ec5ec3437fb99cd1e604a5a45d0b50877b29359c95cfe49eb4c50a4113461ef76367a43911f6761.jpg)

**Comment by hbkwong** [comment]
Hey zhangtreefish, the prompt has been updated! Thanks for the suggestion on this one.
