### ISSUE TITLE
Redux Lesson 1.6 - Typo on Popular Ice Cream Quiz feedback screen

### ISSUE THREAD

**Issue by breakpoint25** [udacity/reactnd-issues#119]
The iceCreamTotals variable is supposed to be an object, but the TRY AGAIN feedback section mentions an array.

What Went Wrong
- Your iceCreamTotals array does not match the expected result

**Comment by hbkwong** [comment]
Good to go! `iceCreamTotals` should indeed point to an object (as in the example), not an array. Thanks for catching that @breakpoint25

@richardkalehoff, I pushed an update to the repo as well
