### ISSUE TITLE
Lesson 1.4 - Replace placeholder image

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#12]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/03b53d7e-ae83-4846-bff3-bc4015cd8d76

Replace the cat placeholder image under the React's Data-flow heading to one that matches this text:

"In the image above, we have two components:

a parent component
a child component"

**Comment by hbkwong** [comment]
Looks like this has since been fixed. Closing it up. Thanks for all your insight Kelli!
