### ISSUE TITLE
Live Help attach file doesn't function

### ISSUE THREAD

**Issue by czeise** [udacity/reactnd-issues#123]
Clicking on the link to browse for a file or dragging and dropping a file onto the specified area does not do anything.

**Comment by hbkwong** [comment]
@czeise Just wanted to check in -- are you still seeing this error?

**Comment by czeise** [comment]
@hbkwong - Yeah, it's still happening for me. [Here's a gif of me trying to drag a screenshot onto the drag-and-drop location](http://g.recordit.co/bdzDv0rBfZ.gif). Nothing happens. After dragging it over, I then try to manually click on the browse link to select a file, but nothing happens. If I try to click on browse first, I get a dialog box to select a file. After selecting a file, the behavior is the same, no indication that anything has happened and then I can't re-click browse or drag a file in.

I'm using Chrome on macOS. I haven't tried a different browser.

Thanks for looking into this!

**Comment by hbkwong** [comment]
Got it. I'll check in with the team tomorrow once I'm back in the office. Thanks for putting together that animation, by the way!

**Comment by hbkwong** [comment]
Thanks for the Slack chat!
