### ISSUE TITLE
Incorrect example of impure function

### ISSUE THREAD

**Issue by samfrances** [udacity/reactnd-issues#124]
I think I have found a mistake in the section on pure functions. This is given as an example of an *impure* function:

```
const tipPercentage = 0.15;


const calculateTip = cost => cost * tipPercentage;

```

But surely, since `tipPercentage` is a *constant* with an *immutable value*, that means that another function can depend on it and still remain pure, does it not? For example, depending on an immutable constant that is another function is never said to compromise a function's purity, e.g.:

```
const tipPercentage = () => 0.15;


const calculateTip = cost => cost * tipPercentage();

```

Possibly the writers ought to have given, as an example of an *impure function*:

```

let tipPercentage = 0.15; \\ Uses let instead of const


const calculateTip = cost => cost * tipPercentage;

```

**Comment by hbkwong** [comment]
Hey @samfrances, totally hear where you're coming from. `calculateTip` still depends on a variable outside of its scope (`tipPercentage`), so we're still dealing with an _impure_ function here. I'll clear things up by switching up the declaration, but in either case, the dependency of an out-of-scope ("outside") variable is compromising the function's purity. Thanks for reaching out on this!
