### ISSUE TITLE
Readable specification has duplicated specification

### ISSUE THREAD

**Issue by Mackiovello** [udacity/reactnd-issues#125]
On https://review.udacity.com/#!/rubrics/1017/view, the line "The voting mechanism works and correctly displays the new vote score after clicking." is written twice under the "Are posts listed correctly and have the desired functionality in a list view?" criteria. 

Also, under "Does the post detail page have desired functionality?", there are two specifications that are clearly overlapping:

> The voting mechanism works and correctly displays the new vote score after clicking for both the post and comments.

and

> The voting mechanism works and correctly displays the new vote score after clicking.

I would delete the second one.

**Comment by hbkwong** [comment]
I put together a JIRA ticket for our team to fix this up. Thanks again @Mackiovello! Enjoy the rest of your week
