### ISSUE TITLE
Lesson 5: Redux Middleware Section 2: What is Middleware? Quiz

### ISSUE THREAD

**Issue by breakpoint25** [udacity/reactnd-issues#126]
The quiz requires knowledge of enhancer and createStore. 

But enhancers are taught in section 3, not section 2.

So why is their a quiz that requires knowledge on a topic that is not yet taught?

**Comment by hbkwong** [comment]
Hey breakpoint25, good catch. Although true, that should not have been one of the choices! The quiz has since been updated.
