### ISSUE TITLE
ES6 Built-ins - Looping Through Maps

### ISSUE THREAD

**Issue by drodeur** [udacity/reactnd-issues#129]
In the text we can read the following code :

`members.forEach((value, key) => console.log(value, key));`

should return :

>  'Evelyn' 75.68
>  'Liam' 20.16
>  'Sophia' 0
>  'Marcus' 10.25

But this is wrong. Replace the code above with this to stay consistent :

`members.forEach((value, key) => console.log(key, value));`

**Comment by breakpoint25** [comment]
I agree

**Comment by hbkwong** [comment]
@drodeur The fix has since been made. Totally with ya on this change -- thanks for chiming in!
