### ISSUE TITLE
Lesson 1.4 Question 2 Wording

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#13]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/03b53d7e-ae83-4846-bff3-bc4015cd8d76

Question 2 starts with this sentence "Now let's say that the FlightPlanner has two child components: LocationPicker and DatePicker. "

It would sound better if "the" is removed before FlightPlanner or if the word "component" is added after FlightPlanner. 

Example:

"Now let's say that the FlightPlanner component has two child components: LocationPicker and DatePicker. "

**Comment by hbkwong** [comment]
Quick fix, and it sounds much better now. Thank you!
