### ISSUE TITLE
ES6 - Lesson 2 - Section 10

### ISSUE THREAD

**Issue by breakpoint25** [udacity/reactnd-issues#131]
Material says to call an function with array destructuring with defaults as the following

`createSundae([undefined, toppings: ['Hot Fudge', 'Sprinkles', 'Caramel']]);`

That doesn't look like a valid array arguments since it has the toppings key like an object would have? 

Shouldn't the code instead be

`createSundae([undefined, ['Hot Fudge', 'Sprinkles', 'Caramel']]);`

**Comment by hbkwong** [comment]
Hi breakpoint25, just closing the loop on this one: the change was pushed in a previous release. Thanks for checking in!
