### ISSUE TITLE
Typo: lesson 11 practice behavioral questions

### ISSUE THREAD

**Issue by earthyearth** [udacity/reactnd-issues#133]

**Comment by earthyearth** [comment]
I just want to report typo on lesson 11 practice behavioral questions 'what motivates you at the workplace?' the second bullet point.
Should be how instead of hot.

**Comment by hbkwong** [comment]
Hi @earthyearth, thanks for checking in! Somehow this got filtered into the board for React issues. Where did you see this typo?

**Comment by earthyearth** [comment]
@hbkwong hi, it's not react's issue, it is in Udacity's personalized career feedback.
