### ISSUE TITLE
Bug in "Create a Reducer" Quiz

### ISSUE THREAD

**Issue by IngenieroLata** [udacity/reactnd-issues#134]
I think a quiz is wrong, can't make ir work even entering the video solution. It's in the "Redux at its core" > "Create Reducers" > "Create a Reducer"

**Comment by hbkwong** [comment]
Hi @IngenieroLata, thanks for reaching out! I wasn't able to reproduce the error with the video's code. Can you take a screenshot of your code, as well as the modal that pops up after hitting submit?

**Comment by hbkwong** [comment]
Closing this for now. Please feel free to Slack me directly if you still run into issues! Let's get this roadblock out of your way

**Comment by becomeLegend** [comment]
Running into issues here also - see my # 157 for a stack trace.
