### ISSUE TITLE
React & Redux - Lesson 5 - Section 4 - Quiz Question

### ISSUE THREAD

**Issue by rckviu** [udacity/reactnd-issues#135]
<img width="1407" alt="screen shot 2017-08-28 at 10 22 50" src="https://user-images.githubusercontent.com/7135676/29757064-a04fb780-8bdb-11e7-88bf-1a3a73cb7bec.png">

There should be four event blocks

**Comment by hbkwong** [comment]
Hey @rckviu, which browser are you using? I'm on Chrome 60 and  unable to reproduce the error just now:
![Screen Shot 2017-08-27 at 8.24.31 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594c5d689185170020b700f2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f46b7191a370f1102f4f5c5e5ecc3c4a4356bcbbd671f3e57862804e0ee4d5655f21976f45a5ee8019bd01ba768c4680b4b98e45d2f42f67b6d5db1063474f4dcbed5727a29f41c95df648e94455a3173061e17f2431.png)

**Comment by rckviu** [comment]
@hbkwong I udpated Chrome to version 60.0.3112.113 and the issue resolved.
Thanks!

**Comment by hbkwong** [comment]
Nice! I'm not 100% that might've been the issue, but I'm glad you can see everything now. Feel free to reach out if you run into anything like this again. Happy coding @rckviu !
