### ISSUE TITLE
Redux Sagas

### ISSUE THREAD

**Issue by vypah** [udacity/reactnd-issues#136]
For further course improvement I would recommend adding redux sagas as part of the course content. That is much more used practice in the industry these days as compared to the thunk approach.

**Comment by vypah** [comment]
https://redux-saga.js.org/

**Comment by hbkwong** [comment]
Hey @vypah, totally with you on this one. What's more: I've seen some recent student interest in this as well, and I'll keep keep it in mind for newer versions of the curriculum. Feel free to reach out to me on Slack if you have any additional feedback.

**Comment by vypah** [comment]
Hey @hbkwong, Thanks for your feedback. While going through the content I really missed this.

**Comment by hbkwong** [comment]
Absolutely. Even if students choose not to use them in projects, it's important to know. They're common in larger-scale apps, after all.

**Comment by hbkwong** [comment]
Closing this issue, but it's on my radar in JIRA for a future update. Thanks again vypah
