### ISSUE TITLE
Readable Project Specifications

### ISSUE THREAD

**Issue by breakpoint25** [udacity/reactnd-issues#137]
There are some errors in the rubrik.

Under the criteria **Are posts listed correctly and have the desired functionality in a list view?**
The following sentence appears twice:
"The voting mechanism works and correctly displays the new vote score after clicking."

Under the criteria **Does the post detail page have desired functionality?**
The following sentence says 'post' when it should say 'comment':
"Listed comments are displayed with author, current score, and a voting mechanism to upvote or downvote the post. Comments should have buttons or links for editing or deleting that comment."

The following sentence states the same thing as sentence proceeding it and should be removed:
"The voting mechanism works and correctly displays the new vote score after clicking."

**_Other comments_**
Posts do not return the comment count, is it advisable the a secondary call be made for each post to obtain the count on the Listed Posts screen?

**Comment by hbkwong** [comment]
Hey @breakpoint25, the duplicate/unnecessary expressions have been removed, and "post" has been correctly updated to "comment." I'll check in with our student services team on that last part for ya. Thank you as always for reaching out. Much appreciated 👍

**Comment by hbkwong** [comment]
Don't want to keep you hanging. I should have an answer for you by tomorrow!

**Comment by SecondProfessionalLife** [comment]
To my mind your change from post to comment was not correct. By this change a comment has now a score of its own, whereas in the project overview it is clearly stated that the voteScore of a comment is "Net votes the post has received (default: 1)". Therefore it is intended that you can only change the score of a post. Due to this description a comment itself does not have a score you can upvote or downvote. Please clarify this ambiguity arose  from your change. Thanks in advance!

**Comment by breakpoint25** [comment]
Good find, the voteScore row under Comments on the Project Overview page also has the copy/paste mistake and needs to be corrected.

Comments indeed have a separate vote value that is not tied to the Posts vote value. This can be seen in the server's code of the default data object in comments.js.

**Comment by forbiddenvoid** [comment]
I fixed that page @breakpoint25 @SecondProfessionalLife. Comments should indeed have their own vote values. Thanks for pointing this out.
