### ISSUE TITLE
Missing content between Lesson 4 and Lesson 5

### ISSUE THREAD

**Issue by jajajames** [udacity/reactnd-issues#138]
Walkthrough navigation with state missing before React Router introduction

**Comment by hbkwong** [comment]
Hey @jajajames, thanks for checking in. Can you elaborate a bit more on this one? Was there any material (or actually, lack of material) preventing you from completing the Contacts app and/or MyReads (or preventing you from learning any content in general)? Let's get these roadblocks out of your way

**Comment by jajajames** [comment]
Yes the learner following along at home is missing a step where he sets up
routing. This causes confusion as he looks through git commits to see what
he missed. Does that explain the issue?
