### ISSUE TITLE
Lesson 1.5 Incomplete sentence

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#14]
This sentence is incomplete "Functional programming has had a large impact on"

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd

**Comment by kellim** [comment]
The heading after the incomplete sentence does say "Array's .map() Method" but it's unclear if the heading is supposed to finish the sentence or not.

**Comment by hbkwong** [comment]
Thanks for the heads up! I just checked, and it seems like it's since been fixed ("Over the past couple of years, functional programming has had a large impact on the JavaScript ecosystem and community."). Closing this one up.
