### ISSUE TITLE
ES6 - Lesson 1 - Quiz: Writing a For...of Loop (1-4)

### ISSUE THREAD

**Issue by raywu** [udacity/reactnd-issues#142]
_Context_

+ code submission review expects `day` to be used within `console.log()`
+ submission error message: `Your for...of loop is missing a variable to keep up with the individual days in the loop`

_Quiz_

*Directions:*
Write a for...of loop that:

+ loops through each day in the days array
+ capitalizes the first letter of the day
+ and prints the day out to the console

Your code should log the following to the console:

> Sunday
> Monday
> Tuesday
> Wednesday
> Thursday
> Friday
> Saturday

_My code submission (to reproduce)_

```
/*
 * Programming Quiz: Writing a For...of Loop (1-4)
 */

const days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

// your code goes here
for (const day of days) {
    let chars = day.split("");
    let firstChar = chars.shift().toUpperCase();
    console.log(firstChar.concat(...chars));
}
```

*Console output:*

```
Sunday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
```

_spoke with a live help person. This code that was provided passed submission review_

```
for (const day of days) {
  console.log(day[0].toUpperCase() + day.slice(1))
}
```

**Comment by raywu** [comment]
Suggestion: the quiz instruction or submission review criteria should change

**Comment by Molecule06** [comment]
agree with raywu's suggestion +

**Comment by hbkwong** [comment]
Totally with you, and I also appreciate the amount of detail you shared @raywu! Adding this to our JIRA board so we see this update in a future release.
