### ISSUE TITLE
React Fundamentals L1-S5 .map() Quiz (suggestion) confused usage of `name`

### ISSUE THREAD

**Issue by fediev** [udacity/reactnd-issues#143]
`name` has different meanings in this quiz. In quiz explanation, `name` means artist name, but in code, `name` means album name. It's not critical, but for intuitive understanding, I think 'album', 'artist' and 'sales' would be better.

**Comment by hbkwong** [comment]
Hey @fediev, totally with you on this one. It's since been updated. Thanks for reaching out!
