### ISSUE TITLE
ES6 - Lesson 2 - Section 11 - Quiz: Using Default Function Parameters (2-2)

### ISSUE THREAD

**Issue by raywu** [udacity/reactnd-issues#144]
_Context:_

+ code submission review provides error message: `Cannot read property 'length' of undefined`
+ code snippet doesn't call `length` and all parameters have default values

_Code Submission_

```
/*
 * Programming Quiz: Using Default Function Parameters (2-2)
 */

// your code goes here
const buildHouse = ({ floors = 1, color = 'red', walls = 'brick' } = {}) => `Your house has ${floors} floor(s) with ${color} ${walls} walls.`;

/*
console.log(buildHouse()); // Your house has 1 floor(s) with red brick walls.
console.log(buildHouse({})); // Your house has 1 floor(s) with red brick walls.
console.log(buildHouse({floors: 3, color: 'yellow'})); // Your house has 3 floor(s) with yellow brick walls.
*/
```

**Comment by raywu** [comment]
![Screen Shot 2017-08-31 at 2.43.44 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a5f2e2788f3b0013b108f7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6457f26b7191a37af116284f5b5b5ecc3c4a4356bcbbd671f3e57862804e0ee4d5655f21976f45a5ee8019bd01ba768c4680b4b98e45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df64fe34c53a71a3461ee762431.png)

**Comment by hbkwong** [comment]
Hey raywu, thanks for checking in. It's a known bug in our system in which the default parameter isn't counted when invoking `.length`, even when it "should" be 1 and not undefined. Not a fan! I've created a JIRA ticket to make sure this gets fixed in a future release. Sorry about the confusion here!

**Comment by preetijessal** [comment]
Try this
function buildHouse({floors= 1, color='red', walls='brick'} = {}){
    return `Your house has ${floors} floor(s) with ${color} ${walls} walls.`;
}
