### ISSUE TITLE
ES6 - Lesson 2 - Section 20 - Quiz direction has a typo

### ISSUE THREAD

**Issue by raywu** [udacity/reactnd-issues#146]
[_Quiz: Building Classes and Subclasses (2-3)_](https://classroom.udacity.com/courses/ud356/lessons/3925704a-be38-4b70-8c8b-a4a812b6a309/concepts/54bdd363-83d7-46e2-81d1-9d1d647a908f)

_Context:_

Directions:

Create a `Bicycle` subclass that extends the `Vehicle` class. The `Bicycle` subclass should override `Bicycle`'s constructor function by changing the default values for `wheels` from `4` to `2` and `horn` from `'beep beep'` to `'honk honk'`.

+ should be: …`Bicycle` subclass should override ~`Bicycle`~ `Vehicle`'s constructor function…

**Comment by hbkwong** [comment]
Hey @raywu, good catch. It's since been fixed, so feel free to refresh. Thanks for checking in!
