### ISSUE TITLE
ES6 - Lesson 3 - Section 15 - `forEach()` loop example can be confusing

### ISSUE THREAD

**Issue by raywu** [udacity/reactnd-issues#147]
_Context_

+ `forEach()` should output key and value to console
+ example: `members.forEach((value, key) => console.log(value, key));`

> 'Evelyn' 75.68
> 'Liam' 20.16
> 'Sophia' 0
> 'Marcus' 10.25

+ the code is technically not wrong, but `value` and `key` are flip flopped and can be confusing

**Comment by hbkwong** [comment]
Thanks for checking in, @raywu. You're right -- they can be called just about anything, but `key, value` probably makes the most sense. They change has since been made!
