### ISSUE TITLE
lesson 3 es6 symbols grammar

### ISSUE THREAD

**Issue by jajajames** [udacity/reactnd-issues#149]
"This will create a unique symbol and store it in sym1. The description "apple" is just a way to describe the symbol, but it can’t be used the access the symbol itself." I think you want to change the last 'the' to 'it'

**Comment by hbkwong** [comment]
Thanks for checking in @jajajames! The following update has been made:

'This will create a unique symbol and store it in sym1. The description "apple" is just a way to describe the symbol, but it can’t be used the access the symbol itself.'

-->

'This will create a unique symbol and store it in sym1. The description "apple" is just a way to describe the symbol, but it can’t be used to access the symbol itself.'

Hope you had a great holiday weekend. Enjoy your week!
