### ISSUE TITLE
Lesson 1.5 - "array function" or "arrow function"

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#15]
Under the Array's .filter() Method heading, it says
"Again, just like with .map() the array function that's passed to .filter() gets called for each item in the names array. " 

Shouldn't it be "arrow function" instead of "array function" that's passsed to .filter()?

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd#

**Comment by hbkwong** [comment]
Great catch! Update has been made. Thanks!
