### ISSUE TITLE
RF L3-S6 PropTypes `npm install --save prop-types` breaks dependencies when `create-react-app` used `yarn` (title edited)

### ISSUE THREAD

**Issue by fediev** [udacity/reactnd-issues#150]
After installing 'prop-types' pakages with `npm install --save prop-types` command for L3-S6 PropTypes, I got an error saying "'react-scripts' is not recognized as an internal or external command ..." and couldn't start app. 

After some inspection, I found that it was because installing package with `npm` removed many packages not in package.json but in yarn.lock. 

I'm not sure it's my npm version problem(my npm version: 5.0.0). But, I think using yarn is a safer solution or at least some additional instruction is needed.

**Comment by fediev** [comment]
+ When using `create-react-app`, `prop-types` is already installed and no need to install it again.

**Comment by hbkwong** [comment]
Yikes - that is odd, @fediev. It sounds like installing a module removes other modules for some reason. Do you still get the same error if you use the `--save-dev` flag to save it into `devDependencies`?

**Comment by fediev** [comment]
This is what I found. 

1. `create-react-app` installs packages and saves full information about installed packages on lock file, not on `package.json`. 

2. If `yarn` is installed, `create-react-app` will use `yarn` and  create `yarn.lock`. If not, it will use `npm` and create `package-lock.json`. 

3. If a generated app is created with `yarn` and has `yarn.lock` not `package-lock.json`, `npm install --save ...` will remove some installed packages that are not needed for packages listed in `package.json` and `npm start` will not work. For `npm` does not consider `yarn.lock`.  

4. In that case, `yarn install` will fix the problem. 

In lesson 2 section 3. Create React App, 'The Yarn Package Manager' block says 'almost every use of yarn can be swapped with npm and everything will work just fine', but above situation is not the case. I think some instruction will be helpful. 

Belows are questions about this on slack, but was not answered fully. 
https://udacity-react.slack.com/archives/C5T15EFLM/p1501459052816176 
https://udacity-react.slack.com/archives/C5T15EFLM/p1499372294077374

**Comment by hbkwong** [comment]
Thanks for chiming in on this one, fediev. We should have more info on this soon in a future release.
