### ISSUE TITLE
Asynchronous JavaScript - APIs

### ISSUE THREAD

**Issue by drodeur** [udacity/reactnd-issues#151]
Asynchronous JavaScript
Ajax with XHR
4. APIs

In the following text :

Also, did you know that [Udacity has an API](https://www.udacity.com/catalog-api)? It's available for anyone to use. We want to make it easy for developers to access and share our catalog of courses.

The udacity API link get us to a 404 page.

**Comment by hbkwong** [comment]
Hey @drodeur, the link to the public-api catalog has been updated. Give it a shot! If you still run into issues, feel free to Slack me directly. Let's get any roadblocks out of your way.
