### ISSUE TITLE
Missing content in Redux lesson 1.3

### ISSUE THREAD

**Issue by becomeLegend** [udacity/reactnd-issues#152]
in how redux improves predictability – you hardly talked about it. you have in the summary:
Redux improves predictability in web apps in several ways:
•	Data is consolidated to one centralized location
•	Components have to request access to that data
•	Data in the store flows in one direction
•	Strict rules are set on how the store can be updated

You haven’t mentioned anything about points 2,3,4. Is there a video missing here?

**Comment by hbkwong** [comment]
Hi @becomeLegend, totally hear where you're coming from. You're not missing any video; that information is just spread across the last section you were in, as well as the current section (i.e., `What is Redux/Why does it exist?` and `How Redux Improves Predictability`). We'll change up the wording to avoid any confusion. If you run into any roadblocks, feel free to reach out on Slack.

**Comment by becomeLegend** [comment]
You gave more information in the summary than in these sections!

**Comment by hbkwong** [comment]
Hi becomeLegend, I'm not sure I follow. "Redux is All About State Management"
and "The Store: A Single Source of Truth" cover information about centralized data (i.e., data in the store) in detail.

I'm with you on the unidirectional data flow in this section though. I'll look to have this information updated soon in a future release.

**Comment by becomeLegend** [comment]
Thanks.

**Comment by hbkwong** [comment]
Just to close the loop: a JIRA ticket has been created to keep this on-radar for a future release. Thanks again for checking in, becomeLegend!
