### ISSUE TITLE
Readable Project - Error on the server code

### ISSUE THREAD

**Issue by jansvigar** [udacity/reactnd-issues#153]
I just realized that there is an error in the server code for getAllPosts
```
function getAll (token) {
  return new Promise((res) => {
    const posts = getData(token)
    let keys = Object.keys(posts)
    let filtered_keys = keys.filter(key => !posts.deleted)
    res(filtered_keys.map(key => posts[key]))
  })
}
```
`!posts.deleted` should be `!posts[key].deleted`. That's why the getAll function always returned all posts even if deleted property is true

**Comment by hbkwong** [comment]
Hey @jansvigar, the [starter code](https://github.com/udacity/reactnd-project-readable-starter/blob/master/api-server/posts.js) reflects the correct answer you shared. If you still run into issues, feel free to shoot me a Slack directly too! Thanks for checking in
