### ISSUE TITLE
BookAPI search() method miss shelf attribute

### ISSUE THREAD

**Issue by lipeRomani** [udacity/reactnd-issues#154]
Project "My Reads".

The search() method dont return shelf attribute in books.

**Comment by breakpoint25** [comment]
it shouldn't

the shelf attribute is relative to your application, not the api

you need to merge the details from your existing data set into the new returned data

**Comment by hbkwong** [comment]
Hi lipeRomani, if you're still running into issues, feel free to shoot me a Slack directly. 

Thanks for all your contributions breakpoint25! In both the Slack channel and on this board. We really appreciate it 👍
