### ISSUE TITLE
Quiz: Using the Rest Parameter (1-5)

### ISSUE THREAD

**Issue by Molecule06** [udacity/reactnd-issues#155]
/*
 * Programming Quiz: Using the Rest Parameter (1-5)
 */

// your code goes here

function average(...nums) {
    let total = 0;
    for(const num of nums) {
        total += nums[num];
    }
    let avg = total / nums.lenght;
}

console.log(average(2, 6));
console.log(average(2, 3, 3, 5, 7, 10));
console.log(average(7, 1432, 12, 13, 100));
console.log(average());

this is as far as I can come up with ... anyone can shine some light into this ... I am trying to use the Rest Parameter to get average of those arrays

**Comment by veronikabenkeser** [comment]
It looks like your code contains a few bugs. Please contact a mentor on Live Help for assistance.
