### ISSUE TITLE
Missing nested data on Normalization page

### ISSUE THREAD

**Issue by rrjamesjr** [udacity/reactnd-issues#158]

**Comment by rrjamesjr** [comment]
I think ...state[bookType][genre][category] is missing in the hierarchy of the reducer function

![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b9e1c4272a5700120154e4/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa7f28d5e629bd4622075d594cac410e584df9fb8c2fafa42062c80d55b98e30063e937f03a6aa8317b500bf208e4c80b2be8c4ec4ee3a37aa.PNG)

**Comment by hbkwong** [comment]
Hi @rrjamessr, `category` has been removed. It was a key from an older version of this snippet, but the state and parts of the reducer didn't get fully converted. Thanks for checking in on this!
