### ISSUE TITLE
RN: JSON wrong format/missing ❝ ❞

### ISSUE THREAD

**Issue by abdennour** [udacity/reactnd-issues#159]
In React-Native course > Lesson 5> 6. App Store Preparation : The given snippet of  `app.json` has wrong format  with two keys : bundleIdentifier & package .. 

Expected ✅ : "bundleIdentifier" ... "package" (add double quotes)

Actual  🚨 :  bundleIdentifier ... package

**Comment by abdennour** [comment]
# Actual : 

```
    "ios": {
     bundleIdentifier: "org.udacifitness.exp",
    },
    "android": {
     package: "org.udacifitness.exp",
    }
```

# Expected 

```
    "ios": {
     "bundleIdentifier": "org.udacifitness.exp",
    },
    "android": {
     "package": "org.udacifitness.exp",
    }
```

**Comment by abdennour** [comment]
Note : 
> The code in github is right.. The wrong format in the flat snippet in the section .

**Comment by hbkwong** [comment]
Good catch. The code in the repo and the screencast are consistent, but I'll update the snippet with the correct strings. Thanks!
