### ISSUE TITLE
Lesson 1.5 - "Tyler" is not longer than 5 characters

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#16]
Under the Array's .filter() Method heading, in the second to last paragraph it says
 "Notice that it only has one name in it now, because both 'Michael' and 'Tyler' are longer  than 5 characters and were filtered out."

Since 'Tyler' is exactly 5 characters long, it would be better to say "5 characters or longer"  instead of "longer than 5 characters"

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd#

**Comment by hbkwong** [comment]
Thanks for the fix, @richardkalehoff! Moving this to 'Done.'
