### ISSUE TITLE
React Native - Lesson 5 - Section 1

### ISSUE THREAD

**Issue by Mark70117** [udacity/reactnd-issues#160]
changes made in video link
https://github.com/udacity/UdaciFitness/commit/8f38bb640f0441383ca906597049190989be853f

should be
https://github.com/udacity/reactnd-UdaciFitness-complete/commit/8f38bb640f0441383ca906597049190989be853f

**Comment by hbkwong** [comment]
The update has been pushed. Thanks for catching this, Mark70117!
