### ISSUE TITLE
React Native - 5.2 - commit does not match video

### ISSUE THREAD

**Issue by Mark70117** [udacity/reactnd-issues#161]
in React Native Lesson 5.2 Geolocation the 4th
'Here's the commit with the changes made in this video' does not match code changes in video.
At a minimum, it is missing  imports from 'expo' and '../utils/helpers'

**Comment by Mark70117** [comment]
https://github.com/udacity/reactnd-UdaciFitness-complete/blob/654fab8ad1502c104a0501adea1819a4f9ab54c1/components/Live.js  does not show the imports

**Comment by Mark70117** [comment]
And imports missing on "View" of Live.js for rest of code changes in video  code listing through out 5.2

**Comment by hbkwong** [comment]
That is odd! Sorry for the confusion, @Mark70117. I'll take a look this afternoon and see what's going on. At the very least, I'll make sure a clarifying message shows up on the page if this becomes a problem. Thank you so much for reporting this!
