### ISSUE TITLE
React Native - 1.4 - Quiz occurs before you learn about answers

### ISSUE THREAD

**Issue by breakpoint25** [udacity/reactnd-issues#163]
The Quiz has answers that are only discussed after the quiz. 

You do not learn that shaking the phone to brings up development menu until you watch the 2nd video or review the details about refreshing.

Overall, using shake to bring up the development menu is actually pretty vague in this section. Since it is really only mentioned to be used for refreshing.

I think this should be discussed before the Quiz occurs and possibly enhanced.

Also providing the shortcuts on Windows and Linux may also be helpful for some people.  It only mentions Mac shortcuts.

**Comment by hbkwong** [comment]
Great points. I pushed an update to change up the ordering this morning . We'll look into adding more to this section to add some more color to the development menu itself. Thanks for checking in as always!
