### ISSUE TITLE
React-Native - 2.3 - Missing word in setence

### ISSUE THREAD

**Issue by breakpoint25** [udacity/reactnd-issues#164]
Near beginning of lesson the following sentence is missing a word.

>  `Just HTML's <div>, <View> components can accommodate several props (e.g. style), and can even be nested inside other <View> components!`

I assume you want it to read "Just like HTML's"

**Comment by hbkwong** [comment]
The update has been pushed. Thanks for the heads up! Hope you had a great weekend.
