### ISSUE TITLE
ES6 - L3 - S6 Set.prototype.add() returns Set, not T/F

### ISSUE THREAD

**Issue by fediev** [udacity/reactnd-issues#165]
Tip section says 'Both methods return true if an item is successfully added or deleted from the Set and false if unsuccessful.'

Set.prototype.add() returns Set, not true or false.

**Comment by hbkwong** [comment]
Hey @fediev, that is true. I'll make sure an update gets pushed to the classroom this afternoon. Thanks for catching that!
