### ISSUE TITLE
Ajax with Fetch formatting error

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#166]
Lesson 3: Ajax with Fetch Section 7: Display Content & Handling Errors 

https://classroom.udacity.com/nanodegrees/nd019/parts/c5795c43-ebd1-4da9-8af9-db1c95ccf9e4/modules/b19830db-a890-435a-9a2c-3f5394b0df08/lessons/7cd5017a-cdce-463f-ba13-e53603fa83eb/concepts/18a6772b-7c45-4f23-8479-dd294633245a

"A couple I can think of are:

issues with the network issues with the fetch request Unsplash not having an image for the searched term" 

(should probably be split up by bullet points)

**Comment by hbkwong** [comment]
Fixed! Somehow the markdown was broken. Thanks @JessicaBettencourt
