### ISSUE TITLE
Example code is the same with/without mapDispatchToProps

### ISSUE THREAD

**Issue by czeise** [udacity/reactnd-issues#167]

**Comment by czeise** [comment]
React & Redux > Reace & Redux > 4. Connect

The `mapDispatchToProps` code examples attempt to show a with and without example of using `dispatch`, but both examples call the method the same way: `this.props.boundUpdateName(this.state.name)`. The first example should be using `dispatch` to call `updateName`.

Full link to location: https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/c7a8f8a7-3922-473d-abc0-52870f9fac67/concepts/ee2b83a1-6f39-4392-be7f-acaaa0719f64

**Comment by hbkwong** [comment]
Hey Craig, great catch. Another student mentioned it here as well: https://github.com/udacity/reactnd-issues/issues/171

I'll go ahead and push an update this afternoon. Thanks again for checking in! Shoot me a message on Slack if you need anything.
