### ISSUE TITLE
No relation between question and answer - React Native - Lesson 2 quiz

### ISSUE THREAD

**Issue by pescamillam** [udacity/reactnd-issues#168]
Personally I don't thing there is a relationship between the question 

What is true about web applications versus native applications? Select all that apply:

and the answer:

Tabs in native iOS applications are generally expected to be found at the bottom of the device screen

**Comment by hbkwong** [comment]
Hey pescamillam, totally with you on that. The "versus" suggests that there's a comparison to be made between the two, when the original intention of the quiz was to qualify statements (true or false) about web applications or native applications. We'll change the wording on that one to clean things up. Thanks for checking in!
