### ISSUE TITLE
Make Criteria more detailed

### ISSUE THREAD

**Issue by lukasz81** [udacity/reactnd-issues#169]
Acceptance criteria is the closest point of reference and a guideline for developer of things that app should include. 
State there that you want books to be fetched from the API, in general be very specific.

**Comment by hbkwong** [comment]
Hey @lukasz81, thanks for checking in! Just wanted to get more details on this one. Is there a particular spot in the instructions that needs clarification? I just went through the Project Overview, which references the [Backend Server](https://github.com/udacity/reactnd-project-myreads-starter#backend-server) in the README. The `getAll` method is described as:

```bash
Returns a Promise which resolves to a JSON object containing a collection of book objects.
```

If it continues to be an issue, let me know! Let's get any roadblocks out of the way immediately.

**Comment by lukasz81** [comment]
Hi @hbkwong , where does it state that? In the Criteria?  Instead of students jumping  between Criteria, Tutorials and readme file in the repo, it should state in one place what is expected from us. Place it all together in detailed acceptance criteria. It will save us lots of time and effort. Hope it helps, thanks.

**Comment by hbkwong** [comment]
Hey Lukasz, I'll forward and discuss this with the student experience team. Thanks for checking in!
