### ISSUE TITLE
Lesson 1.5 - import error in .filter() quiz

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#17]
There's already a similar issue for the .map() quiz, but I'm also getting an import error when running "Test Run" on the .filter() quiz:

<code>Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_idzeozcdpe/main.py", line 2, in <module>
    import studentMain
ImportError: No module named studentMain</code>

If I click the Submit button, it says "Try Again" and also "Thank you for your submission!"

I tested my code for the quiz in the console and it worked so I think the code is correct. I'm not posting my code here since I'm not sure if you want quiz answers on this repo.

Browser: Chrome Version 58.0.3029.110 (64-bit) on Win 7.

Link https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd#

**Comment by hbkwong** [comment]
This one too (in reference to card #18). Thanks again Kelli!
