### ISSUE TITLE
React & Redux 3.4 - Wrong sample code in 'mapDispatchToProps' section

### ISSUE THREAD

**Issue by LonelyPrincess** [udacity/reactnd-issues#171]
I think there's a little typo in **Lesson 3-4** of the **React & Redux** course, in the `mapDispatchToProps` section. In the example where you haven't yet added this parameter to the `connect` method, you do:

```
handleUpdateUser = () => {
  this.props.boundUpdateName(this.state.name)
}
```

Shouldn't it be like this instead? 

```
handleUpdateUser = () => {
  this.props.dispatch(updateName(this.state.name))
}
```

Since we haven't used `mapDispatchToProps` yet in the first example, `boundUpdateName` shouldn't even exist. Feel free to dismiss this issue if I misunderstood something, though.

**Comment by hbkwong** [comment]
Hey @LonelyPrincess, good call. `boundUpdateName` isn't an available prop in the first example, so the dispatch `updateName` should be dispatched directly. 

The update will be pushed later this afternoon. Have a great week!
