### ISSUE TITLE
Make a Udacimeals Starter code for the React-Redux project

### ISSUE THREAD

**Issue by ti-bryce** [udacity/reactnd-issues#172]

**Comment by hbkwong** [comment]
Thanks for the feedback @ti-bryce! I'll keep this in our gameplan for the next version of the React & Redux course. There's already a commit with a basic skeleton, but specifically, what would you like to see in the starter code?

**Comment by hbkwong** [comment]
Closing this for now, but feel free to shoot me a Slack message if you have further feedback!
