### ISSUE TITLE
React Native 2.4 — Bad method name

### ISSUE THREAD

**Issue by JaviEzpeleta** [udacity/reactnd-issues#174]
AsyncStorage > Summary > "clearAll" :  the correct method name is "**clear**"

[React Native docs for "AsyncStorage.clear()"](https://facebook.github.io/react-native/docs/asyncstorage.html#clear)

**Comment by hbkwong** [comment]
Hey @JaviEzpeleta, good catch! That shouldn't have happened. I'll have an update pushed this morning. Thank you as always for your contributions! Let me know if you need anything.
