### ISSUE TITLE
typo: "info" => "results"

### ISSUE THREAD

**Issue by natomato** [udacity/reactnd-issues#178]

**Comment by natomato** [comment]
outside text "Store the new array in a variable called results"

inside text " *   - store the returned data in a new info variable"

location: https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd

**Comment by hbkwong** [comment]
Hey @natomato, the update has been pushed. Good catch! Just to close the loop: the `results` variable is correct (_not_ `info`).
