### ISSUE TITLE
Lesson 1.5 - import error in .filter() and .map() Quiz

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#18]
There's already a similar issue for the `.map()` quiz AND the `.filter()` quiz, but I'm also getting an import error when running "Test Run" on the  `.filter() and .map() Quiz` (the third quiz on the page):

<code>Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_wjssrpnyoo/main.py", line 2, in <module>
    import studentMain
ImportError: No module named studentMain</code>

If I click the Submit Answer button, it says "Try Again" and also "Thank you for your submission!"

I tested my code for the quiz in the console and it worked so I think the code is correct. I'm not posting my code here since I'm not sure if you want quiz answers on this repo.

Browser: Chrome Version 58.0.3029.110 (64-bit) on Win 7.

Link https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd#

**Comment by hbkwong** [comment]
All good! I honestly ran into the same errors last Monday too, and it just needed to be set up more in the back end. Richard has since taken care of it. Thanks again for bringing it up!
