### ISSUE TITLE
React Native 5.4 scheduleLocalNotification(s)Async

### ISSUE THREAD

**Issue by Mark70117** [udacity/reactnd-issues#181]
https://github.com/udacity/reactnd-UdaciFitness-complete/commit/36d2aef256220a7afb0d537ee37aa09719a394c6  line 205 refers to scheduleLocalNotification(s)Async but the API docs refer to scheduleLocalNotificationAsync

**Comment by hbkwong** [comment]
Hey @Mark70117, the fix has been pushed. Thanks for catching that small but crucial typo! Have a great evening.
