### ISSUE TITLE
Typo- Create Actions

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#182]
https://classroom.udacity.com/nanodegrees/nd019beta/parts/058216cd-7eec-481c-8504-976ec423c466/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/782f801d-3bd8-4b2b-b788-608b0fbe1306/concepts/14c65cde-f754-4fc7-bdd5-834b1f788aef

These functions are called actions creators. The term "action creator" makes sense, since it's really just a function that creates and returns an action.

in Lesson 2: Redux at its Core / 2. Create Actions under "Action Creators"

^ the bold bit should spell "action creators", meaning there's a "s" too much.

Ticket #580964

**Comment by hbkwong** [comment]
@JessicaBettencourt - fixed! Thanks for reporting that one.

**Comment by JessicaBettencourt** [comment]
Thanks!
