### ISSUE TITLE
React Native 5.4 ?missing addListener?

### ISSUE THREAD

**Issue by Mark70117** [udacity/reactnd-issues#183]
Can Lesson 5.4 work without a call to 

Expo.Notifications.addListener(listener) ?

Not seeing any notification when I schedule 3 minutes into the future.   But if I place an Notification.addListener with a console log in callback, I see log messages.

**Comment by Mark70117** [comment]
Perhaps it is an iOS issue of the app being in the foreground.  https://forums.expo.io/t/psa-reminder-notifications-in-ios-foregrounded-apps/641.    If so, still feel this should be highlighted.

**Comment by Mark70117** [comment]
Yes, that was the issue.  Notifications do not show up while running the app on iOS.

**Comment by hbkwong** [comment]
Hey @Mark70117, good call. I'll have a fix pushed tomorrow morning at the latest. By the way, I really appreciate the amount of detail in your reports! Thank you as always for your contributions to this community.
