### ISSUE TITLE
typo in video

### ISSUE THREAD

**Issue by csiszi** [udacity/reactnd-issues#184]
In the video, the instructor wrote `type` instead of `typeof` (see attachment in comment)

**Comment by csiszi** [comment]
![typo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55910021093fbf190056500e/125516c66e82c728ace21e0d46fc8d8a2cc0cfeb9ffbb049a15ee4d67304722a7d5cf32e7187e771b9102d535f5f18ab485d5d41f8f09b37b4f46d2ede0356b49b381d66cc2f10abb2831abf07bf21834f80b1bb824fd2a5.png)

**Comment by csiszi** [comment]
I was too fast, he corrects it in the next video.

**Comment by hbkwong** [comment]
Thanks for checking in anyways @csiszi! Hope things are going well in the course for ya.
