### ISSUE TITLE
React-Native, Lesson 3.3, code is missing "export default"

### ISSUE THREAD

**Issue by fade2g** [udacity/reactnd-issues#185]
Für react-native, lession 3.3 the code for "FlexboxExamples" should have "export default" before class.

Otherwise, Android SDK emulator will show Error message:Element type is invalid,.. Check render method of `AwakeInAppDev`

**Comment by hbkwong** [comment]
Fixed! Export expressions have been added to the three `FlexboxExamples` snippets in this section. Thanks for reporting @fade2g
