### ISSUE TITLE
Typo in CC

### ISSUE THREAD

**Issue by csiszi** [udacity/reactnd-issues#186]
See the attachment in the comment (why can't I attach files when I create the issue?)

**Comment by csiszi** [comment]
![typo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55910021093fbf190056500e/125516c66e82c728ace21e0d46fc8d8a2cc0cfeb9ffbb049a15ee4d67304722a7d5cf32e7187e771b9102d535f5f18ab485d5d41f8f09b37b4f46d2ede0356b49b381d66cc2f10a4b2831abf07bf28834880bebc8b4dd2a5.png)

**Comment by hbkwong** [comment]
Hey @csiszi, a pull request has been made. Once it gets merged, all instances of "GSX" should be updated (unfortunately there were a few more than just in this video). Thank you as always for your reports!
