### ISSUE TITLE
Readable - server-side error when editing a comment

### ISSUE THREAD

**Issue by josenaves** [udacity/reactnd-issues#188]
I have found an issue on EDIT COMMENTS api (backend server for Readable project).

Here is the request:

URL: http://localhost:5001/comments/6ni6ok3ym7mf1p33lnez 
Request Method:PUT 
Body: {timestamp: 1506040172500, body: "It's now or never !!!!!!"}

Getting this: TypeError: Cannot set property 'timestamp' of undefined at Promise (/home/josenaves/Projects/readable/backend/comments.js:115:32) at Object.edit (/home/josenaves/Projects/readable/backend/comments.js:112:12) at app.put (/home/josenaves/Projects/readable/backend/server.js:266:14) at Layer.handle [as handle_request] (/home/josenaves/Projects/readable/backend/node_modules/express/lib/router/layer.js:95:5) at next (/home/josenaves/Projects/readable/backend/node_modules/express/lib/router/route.js:137:13) at /home/josenaves/Projects/readable/backend/node_modules/body-parser/lib/read.js:130:5 at invokeCallback (/home/josenaves/Projects/readable/backend/node_modules/raw-body/index.js:262:16) at done (/home/josenaves/Projects/readable/backend/node_modules/raw-body/index.js:251:7) at IncomingMessage.onEnd (/home/josenaves/Projects/readable/backend/node_modules/raw-body/index.js:307:7) at emitNone (events.js:86:13) at IncomingMessage.emit (events.js:186:7)

**Comment by josenaves** [comment]
@hbkwong is it already fixed ?

**Comment by hbkwong** [comment]
@josenaves - yep, it had since been fixed. If you're still running into issues, let me know! Have a great weekend.
