### ISSUE TITLE
Lesson 2.1 - Next page loading while reading text

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#19]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/9d9d9885-c3c7-4296-ab29-ba51045d7615

After I watched the video, the text below it disappeared when I was in the middle of reading it as the next page in the lesson automatically loaded. 

I realize now that the student is expected to click "Stay Here" after the video is over if they want to stay on the page, but others might have the same issue as I did where they don't realize they need to click "Stay Here" as they naturally just try to read the text below the video after the video is over.

I would suggest not automatically loading the next page and requiring the student to click the next button to move on to the next page when they are ready.

**Comment by karlud** [comment]
I've inserted an empty text atom above the video to stop the full-screen behavior from preventing reading the text.
