### ISSUE TITLE
Pure Functions 2nd Video- Typo

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#190]
https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/b17ccf2f-3f89-4c38-91ae-bd67c083bba2/concepts/154f1d72-c267-4072-bab9-30a92bedcf63#

Lesson 1: Why Redux? 5. Pure Functions 2nd Video

There is a typo on the video. `let = ...` is used. (confirmed by Tyler via Twitter) Can we add info regarding this typo below the video?

**Comment by hbkwong** [comment]
Agreed. You can let students know that an update will be pushed by this afternoon at the latest. Thanks for the heads up @JessicaBettencourt!
