### ISSUE TITLE
<SectionList/> forgotten

### ISSUE THREAD

**Issue by this-miguel** [udacity/reactnd-issues#191]
Problem: I think you missed explanations about <SectionList/> in the video about lists sin the react native section, lesson 2, part 3 Common React Native Components

Attempt: I'm just writting to let you know.

**Comment by this-miguel** [comment]
Problem: I think you missed <SectionList/> explanations  in the video about list sin the react native section, lesson 2, part 3 Common React Native Components

Attempt: I'm just writting to let you know.

**Comment by hbkwong** [comment]
Hey @this-miguel, good catch. Its implementation is a little bit different that of, say, `FlatList`. I've since updated the lesson to reflect `SectionList`, even though it's not necessarily used in the in-class project. Thanks for chiming in - enjoy the rest of your week!
