### ISSUE TITLE
git L9-S3, wrong `git remote rename` args order

### ISSUE THREAD

**Issue by fediev** [udacity/reactnd-issues#192]
In 'Resetting Remote Names',

```sh
git remote rename mine origin
git remote rename source-repo upstream
```

Correct order is `git remote rename <old> <new>`.

**Comment by hbkwong** [comment]
Hey @fediev, just wanted to get more details on this one. As I understand it, this section details resetting remote names (i.e., returning them back to their original/default names after the above example's renaming). It looks like the order still applies, as their <origin> ("old") and <destination> ("new") are now reversed.

**Comment by fediev** [comment]
Sorry, I misunderstand the intention of the commands.

**Comment by hbkwong** [comment]
No worries! If you still run into typos/errors, just let us know. Thanks again for reaching out
