### ISSUE TITLE
Create A Reducer Quiz validation fails

### ISSUE THREAD

**Issue by yayoifw** [udacity/reactnd-issues#193]
When entering the correct solution (posted below the Quiz section) into Quiz and click "SUBMIT ANSWER", it comes back with "Try Again" with "the returned data does not match the expected output." in What Went Wrong section.

**Comment by yayoifw** [comment]
Lesson 2: Redux At Its Core
3. Create Reducers
Quiz: Create A Reducer

**Comment by hbkwong** [comment]
Hey @yayoifw, thanks for writing in. I'm checking in on our tests right now -- keep you posted!

**Comment by hbkwong** [comment]
Hey @yayoifw, I wasn't able to reproduce the error with the solution video's reducer method. Try hitting RESET QUIZ and submitting the solution again. If you still run into errors, let me know! You are welcome to Slack me too! Let's get this roadblock outta your way.
