### ISSUE TITLE
getMetricMetaInfo is imported from helpers but helpers doesn't have getMetricMetaInfo function or object defined

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/reactnd-issues#194]
4. React Native => Up and Running with React Native => 3. Dev Environment Setup => #Section: The Environment

Here in `utils/_calendar.js`, `getMetricMetaInfo` is imported from `helpers` but `getMetricMetaInfo` is not defined in `helpers`. So this is somewhat confusing.

Link: https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/6c4d629a-f390-4591-a54b-ba75d505b619/concepts/df46c5a1-bf94-4045-a3de-304b14572b2c

**Comment by hbkwong** [comment]
Hey ravikumarseth, an update has been pushed. Feel free to refresh! Thanks for reporting this one.

**Comment by ravikumarseth** [comment]
Hey @hbkwong , the getMetricMetaInfo function added here needs some modifications as styles have not been defined here.

I also realised that the getMetricMetaInfo function was made in one of the later video, so replacing the function with a comment saying that the function will be added later will also be helpful.
