### ISSUE TITLE
Typo: React Native / Lesson 4 / StackNavigator

### ISSUE THREAD

**Issue by csiszi** [udacity/reactnd-issues#195]
Note that a `navigation` prop is passed to the stateless functional `Home` component, which allows navigation **to another to another** route.

**Comment by csiszi** [comment]
![React_-_Udacity.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55910021093fbf190056500e/125516c66e82c728ace21e0d46da919b2096bce4b0dcbb42a754e48d6b0a65633b0ba92e7391a172fd172255575f1bfd130c5612feff8b2ba6e03b798f5e0ee9d87f4366846c4ff8e7df46f554f832815d87b6b68b49c0ef3e25e38e8d4e3e1d000ac4.png)

**Comment by hbkwong** [comment]
Hey @csiszi, good catch. The fix has been made. By the way, thank you again for all your contributions to this board! Definitely appreciate all these. Have a wonderful weekend!
