### ISSUE TITLE
Redux Lesson 2.2 - reference create-react-app lesson #

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#196]
In the Redux course, Lesson 2 - #2. Create Actions:

Under "Starting the Project", it mentions to check out the previous React Fundamentals course again for a refresher on create-react-app. It would be helpful to include the lesson number/title in React Fundamentals that you can find the create-react-app info in. A link would be helpful too, but not if it might change and cause a dead link. 

Link: https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/782f801d-3bd8-4b2b-b788-608b0fbe1306/concepts/14c65cde-f754-4fc7-bdd5-834b1f788aef

**Comment by hbkwong** [comment]
Noted! The update has been pushed. I do agree that links are useful, but things may change with updated versions. There are a few spots throughout the entire Nanodegree program that could absolutely use 'em, though.

Have a great weekend @kellim!
