### ISSUE TITLE
React Native. Lesson 3.4. Jest fails after importing udacifitness-calendar

### ISSUE THREAD

**Issue by kunal-mandalia** [udacity/reactnd-issues#197]

**Comment by kunal-mandalia** [comment]
It looks like jest is having problems due to the `ref={(c) => this.listView = c}` on line 247 in `/node_modules/udacifitness-calendar/src/calendar-list`. E.g. removing this line and adding a mock `this.listView = { scrollTo: () => {} }` causes the tests to pass (of course it makes the calendar unusable). Tried raising an issue on tyler's github but it seems locked down.

**Comment by hbkwong** [comment]
Hey Kunal, thanks for checking in. I'll keep this on the map for a future update. In the meantime, feel free to report any other issues you run into. I'll keep a lookout in the Slack group as well.
