### ISSUE TITLE
typo: "dopts" => "adopts"

### ISSUE THREAD

**Issue by natomato** [udacity/reactnd-issues#198]
near the bottom of https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/b17ccf2f-3f89-4c38-91ae-bd67c083bba2/concepts/b0e2a51d-6ad3-4d28-84a3-cc65b639dab1

**Comment by hbkwong** [comment]
Fixed! Thanks for reporting this, @natomato.
