### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by Scriptonita** [udacity/reactnd-issues#199]
Lesson 2 - The code from this commit https://github.com/udacity/reactnd-UdaciFitness-complete/commit/aa767680f50fb26e7e8201fd6a664dfd49f50ac9 
set icon colors to 'White', the same color that background, this color in video is "black"

**Comment by hbkwong** [comment]
Hi Scriptonita, thanks for reporting this. I've added some clarifying text to the page, but I'll keep this on the roadmap to refresh the commit link in a future update. Enjoy the rest of your week!
