### ISSUE TITLE
Typo/Grammar Issue in Lesson 1 #5 - extra "it"

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#2]

**Comment by kellim** [comment]
Under the Array's .map() heading, this part sounds awkward : "If you're not familiar with it, JavaScript's Array .map() method, it gets called on an existing array..." 
This would sound better as "If you're not familiar with JavaScript's Array .map() method, it gets called on an existing array..."

**Comment by forbiddenvoid** [comment]
Please add a link to the page. Thanks!

**Comment by richardkalehoff** [comment]
Fixed!
