### ISSUE TITLE
Lesson 2.2 Videos with repeated content

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#20]
The first 3 videos on the page look like they contain a lot of the same content.

The second video is directly under the first video without any text between them and looks like you may only want to keep one of the videos?

The third video under Question 1 looks like it has the same content as part of the first video.

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/d9831309-352a-4e04-83f3-ac3e4e8cac76

**Comment by karlud** [comment]
I don't see any duplicate video in this particular page. Maybe @richardkalehoff already cleaned it up!
