### ISSUE TITLE
Typo on TabNavigation page

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/reactnd-issues#200]
Typo on line
`Import { TabNavigator } from 'react-navigation';`

`Import` written instead of `import`

Link: https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/c66f0f4f-227b-4f3b-a7a3-483200f3bc12/concepts/172e4b01-a540-4893-8472-4a1196207eae

**Comment by hbkwong** [comment]
Yikes -- that is embarrassing! Small detail, but it makes a huge difference. I've since pushed an update change, so feel free to refresh this afternoon. Thanks for reporting this one, @ravikumarseth

**Comment by ravikumarseth** [comment]
Hey @hbkwong , same Typo on StackNavigator and DrawerNavigator pages.

Links:

 1. [StackNavigator]( https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/c66f0f4f-227b-4f3b-a7a3-483200f3bc12/concepts/2c0e8dfc-1f70-4712-a33c-b5ac85f44f18)

 2. [DrawerNavigator](https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/c66f0f4f-227b-4f3b-a7a3-483200f3bc12/concepts/6b6fcd53-daa0-4dc8-995a-46a006044e59)

**Comment by hbkwong** [comment]
Good to go! Thanks again @ravikumarseth
