### ISSUE TITLE
readable project: data missing from API?

### ISSUE THREAD

**Issue by Courtney2511** [udacity/reactnd-issues#201]
the project requirements ask for a comment count for each post to visible on the post list view.  This data is not included in the post object, and is only available by a call to the endpoint for each individual posts comments.

**Comment by hbkwong** [comment]
Hey @Courtney2511, thanks for checking in during office hours today. I've since created a JIRA ticket on this one to make sure the server gets updated in a future release. If you have any questions in the meantime, feel free to reach out! Have a wonderful weekend :]
