### ISSUE TITLE
Quiz without correct answer

### ISSUE THREAD

**Issue by ricardosbarbosa** [udacity/reactnd-issues#202]
Part 5 React Native -> Topic 3 -> Lesson 2
Any combinations of checkboxes not works.

Language (pt-br)

**Comment by hbkwong** [comment]
Hey @ricardosbarbosa, just wanted to check in. Which combination of choices do you feel like should be the correct solution?

**Comment by ricardosbarbosa** [comment]
number 1 and 4,
but I have tried all the 16 combinations possible.
![captura de tela 2017-10-18 as 13 46 36](https://user-images.githubusercontent.com/1226982/31732537-3e0bc378-b40f-11e7-9dd3-7d271e3eea33.png)

**Comment by hbkwong** [comment]
Hey @ricardosbarbosa, thanks for reporting this one. Totally with you -- 1 and 4 should absolutely be the correct choices. I've since pushed an update. Refresh, give it a shot again, and let me know how it goes!

**Comment by ricardosbarbosa** [comment]
[image: Captura de Tela 2017-10-18 às 14.44.30.png]Now it works!


Em qua, 18 de out de 2017 às 14:32, Andrew Wong <notifications@github.com>
escreveu:

**Comment by hbkwong** [comment]
Perfect. Enjoy the rest of your week Ricardo 😄
