### ISSUE TITLE
Redux Lesson 3.3 - add space

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#203]
In Redux lesson 3.3, in the sentence directly under the video, it looks like there's no space between a and vegetable.

https://classroom.udacity.com/nanodegrees/nd019beta/parts/058216cd-7eec-481c-8504-976ec423c466/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/c7a8f8a7-3922-473d-abc0-52870f9fac67/concepts/eb68392e-863d-4728-99cc-f47b0dfdea85

**Comment by kellim** [comment]
Screenshot of how the sentence with the issue looks for me-
![image](https://user-images.githubusercontent.com/2024584/31848109-759ab714-b5df-11e7-8ceb-d42639f60231.png)

**Comment by hbkwong** [comment]
Fixed! There was an issue with the markdown, but the update has since been made. Thanks again @kellim
