### ISSUE TITLE
Code incorrect because of a typo

### ISSUE THREAD

**Issue by SecondProfessionalLife** [udacity/reactnd-issues#204]
In React Native, Lesson 5 (Native Features), in the second of three videos at minute 4:01 there is a typo in the code: tomorrow.setMintutes(0). Clearly the correct version is tomorrow.setMinutes(0). Same issue in the project code at Github in braches useLocalNotification and setLocalNotification. Best regards Gregor

**Comment by SecondProfessionalLife** [comment]
Typo in my post: instead braches please insert branches

**Comment by hbkwong** [comment]
Hey SecondProfessionalLife, good catch. I've since updated the link to the code for the video in question, and I'll go ahead and update the rest as well. Thanks for reporting this!
