### ISSUE TITLE
Github Link

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#205]
https://classroom.udacity.com/nanodegrees/nd019/parts/9f20ce1b-fddc-4c28-b809-38aa63eab715/modules/e438b04c-2e3c-4438-a0ba-dee831147801/lessons/32374840-482a-4188-bfe7-ebf566a6c210/concepts/e223d2dd-93f8-47bb-83cb-cb4861a74806

The comment feedback hyperlink for Github in lesson #1 section #4 goes to the github.com instead of a specific repo.

**Comment by hbkwong** [comment]
Hey @JessicaBettencourt, did you mean the link in the sentence "Anyone with a GitHub account can flag issues with content."? I think that one is supposed to go to just github.com to sign up/log in, since students are provided with the link to the specific Waffle board already

**Comment by JessicaBettencourt** [comment]
Not quite sure what the student meant, but that makes sense. Thanks!

**Comment by hbkwong** [comment]
Sounds good! If something else comes up, let me know. Otherwise, the page LGTM 👍
