### ISSUE TITLE
React Native, Lesson 5.2, Live.js Bug

### ISSUE THREAD

**Issue by chrislzm** [udacity/reactnd-issues#207]
In this commit: https://github.com/udacity/reactnd-UdaciFitness-complete/commit/0b092b57b530fd6b2d9e9577dd299351e74df75f

Component state property "coords" should also be set to something other than null e.g. { altitude: 1, speed: 1}, otherwise a crash occurs when it tries to get the coords.altitude and coords.speed properties of this null object.

**Comment by hbkwong** [comment]
Agreed. I'll make sure this is noted for students in the curriculum. Thanks for bringing this to our attention @chrislzm!
