### ISSUE TITLE
Lesson 4 - 4. Finish the app - Incomplete changes to this video

### ISSUE THREAD

**Issue by miguelangel** [udacity/reactnd-issues#208]

**Comment by miguelangel** [comment]
Hi!

At __Lesson 4 - 4. Finish the app!__,  I have noticed that there is one line of code missing at the 'changes to this video' [link](https://github.com/udacity/reactnd-udacimeals-complete/commit/823876c8e3b669c0338f630fa50120adb7168f6f)

I am referring to line 18 of __src/components/App.js__:
> loadingFood: false,

I hope it helps!

Have an udacious day!

Miguel Angel

**Comment by hbkwong** [comment]
Agreed! I've added a note in the curriculum to make sure it's highlighted for students. Thanks for bringing this to our attention Miguel!
