### ISSUE TITLE
Lesson 5: 6. App Store Preparation

### ISSUE THREAD

**Issue by Scriptonita** [udacity/reactnd-issues#209]
Last video not working. At 8 seconds show an error.

**Comment by hbkwong** [comment]
Hey @Scriptonita, thanks for checking in. I'm actually unable to reproduce the error with the last video on that page. Are you able to view the video directly on YouTube?

**Comment by Scriptonita** [comment]
Hi Andrew.

Attached a capture from Udacity an another from Youtube.





2017-10-31 2:39 GMT+01:00 Andrew Wong <notifications@github.com>:

**Comment by hbkwong** [comment]
Hi @Scriptonita, can you post the images directly to this thread? I'm not sure if the emailed reply attached the images correctly. Thanks for sticking with this one! Let's get down to the bottom of this together.

**Comment by Scriptonita** [comment]
Hi, today is working.

But thiese are the images:

![error-udacity.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a944addc6e6200135d8c1d/125516c66e82c728ace21e0d46ed86882c90cebc8be8bc4ab044b2d86b56357c2301a03f32dfa17de61623510a0e1cf8480e5d42fef9897da1bf39728f5802ffcd7f1d2598694ef1e1c84afd13b0328a478fb7b98a45c5eb3b26e08d8748360c48.jpg)
![error-youtube.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a944addc6e6200135d8c1d/125516c66e82c728ace21e0d46ed86882c90ceb080fcab56a658b2d86b56357c2301a03f32dfa17de61623510a0e1cf8480e5d42fef9897da1bf39728f5802ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98a45c5eb3b21e78a864c360c48.jpg)

**Comment by hbkwong** [comment]
That's great, thanks for the follow-up. If you run into issues in the future, feel free to open up another issue (or just shoot me a message on Slack). Enjoy the rest of your week!
