### ISSUE TITLE
Lesson 2.3 Repeated video content

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#21]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/2732ebd0-5868-4c37-ad72-891a367c368f

The third video has repeated content (installing create-react-app) from the second video.

**Comment by asparr** [comment]
@richardkalehoff I think the third video on this page can just be removed; it looks like it is only the screencast portion of this concept, which was combined with headshots in video #2 on the page. So, video 3 is 100% duplicated content, this may be intentional, I'm not sure though

**Comment by karlud** [comment]
Agreed with @asparr. Removed duplicate video. The removed video has youtube id = amS78NATSpk in case it needs to be restored.
