### ISSUE TITLE
Feedback for Native

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#210]
While the instructors did a good job, I feel very underwhelmed at the lack of content of vanilla React Native. While Expo is a good way to get started, most apps will require some level of native linking and ejecting from Expo. I wished the lesson talked more about: 
1.) Native Navigation Libraries - Wix and AirBnb's libraries and how to integrate inside an existing (brownfield) app 
2.) How to use Expo libraries (which I think are very cool) if you have an existing app. I know you can't use Push Notifications, but can you use Local Notifications. Can you add expo to your package.json 
3.)How can you create (or even integrate) with native components. What exactly is react-native link?”
4.)Testing. I wish there was a section on both Unit Testing and UI testing with React Native.

Ticket #608809

**Comment by hbkwong** [comment]
Thanks for sending this over @JessicaBettencourt! We already have plans for future versions of course 1 and 2 in JIRA, so I'll create a new ticket for course 3 gameplanning as well.

**Comment by hbkwong** [comment]
Just to close the loop: these were added to the feedback log. Thanks again for sharing, Jessica!
