### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by castelobranco** [udacity/reactnd-issues#211]
There is a broken link on Lesson 3/State Management/Functional Components:

ES6 - JavaScript Improved => https://www.udacity.com/course/es6-javascript-improved--ud356

**Comment by hbkwong** [comment]
Hey @castelobranco, thanks for the report! I'm actually unable to reproduce the error with the link you provided nor with the page itself. What are you seeing once you click the link?

**Comment by castelobranco** [comment]
The link is this one: For further reading, feel free to check out *ES6 - JavaScript Improved* to explore the latest features and improvements to the language.

I see a 404 error.

**Comment by hbkwong** [comment]
@castelobranco, after clicking the link, do you immediately see a 404 error? As long as you have an account at Udacity, you should be able to view the course (i.e., it's a free course).

**Comment by castelobranco** [comment]
Hummm. I think I know what the problem is. I am located on Brazil and as soon as I click the site is being redirected to https://br.udacity.com/course/es6-javascript-improved--ud356. And now I am having a 403 error instead of 404. It is realling annoying being redirected to brazilian version of the site. I would like not being redirected (but maybe this is another issue to open -  =D).

**Comment by hbkwong** [comment]
@castelobranco, good catch! That should be it. I don't have too much much visibility on localization and how redirects are handled, so I recommend sending an email to the support team (support@udacity.com) to check it out. If you're still stuck, feel free to shoot me a message directly on Slack. ES6 has some _awesome_ and powerful features, so let's get this roadblock out of your way as soon as we can.

**Comment by castelobranco** [comment]
OK. Thanks!
