### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by castelobranco** [udacity/reactnd-issues#212]
We have a typo on the Lesson 5, topic 8 from React Fundamentals part. 

It reads "Course Outro" instead of "Course Summary". 

I am located in Brazil but I am taking the english version of this course. "Outro" is a portuguese word and it appears that is a localization problem.

**Comment by castelobranco** [comment]
[Uploading Screenshot 2017-11-11 13.57.47.png...]

**Comment by hbkwong** [comment]
Hey @castelobranco, in the English localization, we meant "outro" as the "closing section." If there any issues in the Portuguese localization, let me know and I'll make sure we get it resolved right away. Thanks for checking in, and enjoy the rest of your weekend!
