### ISSUE TITLE
Readable API Endpoint - DELETE(Post)

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/reactnd-issues#213]
[Link](https://github.com/udacity/reactnd-project-readable-starter/tree/master/api-server)

Usage deleting post says:
```
Sets the deleted flag for a post to 'true'. 
Sets the parentDeleted flag for all child comments to 'true'.
```

So in practice the server should return the post details with `deleted` property being set to `true`.

Currently `getByCategory` and `getAll` functions remove the deleted posts from result (this feature is good). But `get`(by id) returns an empty object if the post is deleted. And `get` (by id) gives an error if the post_id passed is invalid (expected behavior ).

```
function get (token, id) {
  return new Promise((res) => {
    const posts = getData(token)
    res(
      posts[id].deleted
        ? {}
        : posts[id]
    )
  })
}
```
So to manage consistency, it might be good if `get` (by id) returns an `error` or post detail with `deleted` property set to `true`.

**Comment by hbkwong** [comment]
Hey @ravikumarseth, definitely with you on this one. It's not a dealbreaker for the project, but to drive consistency, `get` can be updated as well. We're open to pull requests, so feel free to submit one and we'll be on it right away!
