### ISSUE TITLE
typo in lesson text

### ISSUE THREAD

**Issue by xiaoju** [udacity/reactnd-issues#214]
at 'react native' > 'lesson 5 native features' > '2 geolocation' > above video 'ND019 C3 L5-10 - Live-AskPermission',
the lesson text is missing the 's' in 'Permissions': 
import { Location, Permission } from 'expo';

**Comment by hbkwong** [comment]
The issue has since been fixed! Definitely need to make sure you're importing the right stuff. Thanks for bringing this to our attention, @xiaoju. Have a wonderful weekend!
