### ISSUE TITLE
"Why React?" Unidirectional data flow image is stretched

### ISSUE THREAD

**Issue by muhammad-saleh** [udacity/reactnd-issues#215]
In React Fundamentals > Why React? > Unidirectional data flow
There's an image showing how the unidirectional data flow works
This image is really stretched and it doesn't have the correct aspect ratio

**Comment by hbkwong** [comment]
Hey @muhammad-saleh, I wasn't able to reproduce the error (Mac, using Chrome 62). If you're still seeing stretched images, feel free to open up another ticket. You're welcome to Slack me directly as well! Thanks again for checking in!
