### ISSUE TITLE
React Is "Just JavaScript" .filter() quiz fails on correct answer

### ISSUE THREAD

**Issue by Celebes** [udacity/reactnd-issues#217]
Hello, I submitted code:

const results = musicData.map(m => m.name).filter(n => n.length >= 10 && n.length <= 25);

And it didn't pass. It said I didn't use filter() method and that my result set is wrong, but it gives exactly the same results as:

const results = musicData.filter(m => m.name.length >= 10 && m.name.length <= 25);

Which passed

**Comment by hbkwong** [comment]
Hi @Celebes, thanks for checking in! I'm getting a different result with those snippets. The first produces an array of string, and the second produces an array of objects. When calling filter in the first version, what are you filtering over?

**Comment by Celebes** [comment]
Right, my bad
