### ISSUE TITLE
Defaults & Destructuring Possible Typo

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#218]
https://classroom.udacity.com/nanodegrees/nd019/parts/290ec447-6555-41bf-ac39-457220a09aae/modules/9c5b7af0-0943-4d6e-b672-520440885aba/lessons/3925704a-be38-4b70-8c8b-a4a812b6a309/concepts/5368e2c8-157b-4c15-8aa8-e06a699e9798

"Generating a grid of ..." instead of "Generates a ...." 

Ticket #636337

**Comment by hbkwong** [comment]
Fixed! Thanks for the heads up @JessicaBettencourt
