### ISSUE TITLE
Object.values not recognised as valid Javascript

### ISSUE THREAD

**Issue by andreimc** [udacity/reactnd-issues#219]

**Comment by andreimc** [comment]
have a student stuck on: Iteration & Iterable Protocols, lesson 3.4, ES6 with the following answer:  `const james = { name: 'James', height: '5\'10"', weight: 185 }; const jamesValues = Object.values(james);` and he gets this error message: There's your uninterrupted code block. Anyway, it's saying "Object.values is not a function at Object" when clearly it is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

**Comment by hbkwong** [comment]
Hey @andreimc, thanks for the heads up. `Object.values()` was just added to the official spec this year, and our current version of Node doesn't quite support it yet. But even though `Object.values()` does indeed get the intended result, it's not what the quiz is testing for. Hope this helps!
