### ISSUE TITLE
Lesson 2.3 Incomplete content in recap

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#22]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/2732ebd0-5868-4c37-ad72-891a367c368f

Under the create-react-app Recap heading, the second sentence just says "It..."

**Comment by hbkwong** [comment]
Just completed the Recap section. Good catch! Thank you Kelli
