### ISSUE TITLE
Search example in MyReads project description is not one of the allowed terms

### ISSUE THREAD

**Issue by sarah-maris** [udacity/reactnd-issues#220]
The search example in the MyReads project description:  https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/1c3110e6-46f7-4929-8cf4-8332afbbaadf/lessons/5d31386c-8c1c-4f32-974d-6bf3c1062cba/concepts/e7df4589-29d8-4d49-b760-a1db72d6cbdb  

shows the user searching for Lord of the RIngs:

![image](https://user-images.githubusercontent.com/6298143/33885485-78ef90b4-df11-11e7-900c-149bc4274a3b.png)

But that title is not in the list of Search Terms:

'Android', 'Art', 'Artificial Intelligence', 'Astronomy', 'Austen', 'Baseball', 'Basketball', 'Bhagat', 'Biography', 'Brief', 'Business', 'Camus', 'Cervantes', 'Christie', 'Classics', 'Comics', 'Cook', 'Cricket', 'Cycling', 'Desai', 'Design', 'Development', 'Digital Marketing', 'Drama', 'Drawing', 'Dumas', 'Education', 'Everything', 'Fantasy', 'Film', 'Finance', 'First', 'Fitness', 'Football', 'Future', 'Games', 'Gandhi', 'Homer', 'Horror', 'Hugo', 'Ibsen', 'Journey', 'Kafka', 'King', 'Lahiri', 'Larsson', 'Learn', 'Literary Fiction', 'Make', 'Manage', 'Marquez', 'Money', 'Mystery', 'Negotiate', 'Painting', 'Philosophy', 'Photography', 'Poetry', 'Production', 'Programming', 'React', 'Redux', 'River', 'Robotics', 'Rowling', 'Satire', 'Science Fiction', 'Shakespeare', 'Singh', 'Swimming', 'Tale', 'Thrun', 'Time', 'Tolstoy', 'Travel', 'Ultimate', 'Virtual Reality', 'Web Development', 'iOS'

 so the search will fail when a student tries to replicate it.  

This is confusing to students who think their app needs to work like the example.   Can you either change the image or add "Lord of the RIngs" and "Tolkien" to the Search Terms?

**Comment by hbkwong** [comment]
Hey @sarah-maris, thanks for catching that. The description has since been updated! Have a wonderful holiday weekend
