### ISSUE TITLE
Requeriments to run React Native apps in real devices

### ISSUE THREAD

**Issue by LonelyPrincess** [udacity/reactnd-issues#222]
Lesson 1.3 for the React Native course is missing some information on how to set up everything to run our apps on real devices. 

Apart from the links to the native Expo apps, it would be nice to include a paragraph mentioning how to avoid network problems when trying to run React Native apps by using Expo in our phone.

The two steps required to successfully run the React Native apps in the device are the following: 

- **Have the device connected to the same network as the computer** in which the application server is being run.

- If the computer has some Firewall enabled, include a new rule to **allow incoming connections to ports 19000, 19001 and 19002**. If connections to any of these ports are blocked, the Expo app will fail to run our application in the device. 

The first one of these requeriments is briefly mentioned in one of the videos, but the Firewall issue is certainly worth including as an alert note somewhere in the lesson, as it's likely to happen to anyone using Expo for the first time.

**Comment by veronikabenkeser** [comment]
Hi @LonelyPrincess! This is great feedback, and I will pass it along to our team. We are always looking for ways to improve our program and ensure that our students have the best possible learning experience, so please don't hesitate to reach out in the future. The best way to submit program feedback is to email react-support@udacity.com. (The Waffle Board is meant to keep track of code bugs and bugs in the already existing content.) I look forward to hearing more about your experience!
