### ISSUE TITLE
React Mentor joining the Udacity organisation

### ISSUE THREAD

**Issue by jch254** [udacity/reactnd-issues#223]
Kia ora (hi all),

I love what you're doin with Udacity! It's a fantastic platform and has expanded my knowledge base. I've been a React ND classroom mentor for over three months now, wanting to help out wherever possible, would it be possible to be added to the Udacity GH org?

Cheers, keep it up!

**Comment by hbkwong** [comment]
Hi Jordan,

Thanks for reaching out! Unfortunately, access to the GH org is reserved for engineers and teams developing content. If you do see a project you'd like to contribute to, definitely feel free to submit a PR as well. Thank you for what you do and keep crushing it! Have a wonderful holiday weekend
