### ISSUE TITLE
Typo Implementing Middleware

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#224]
https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/84a3ef1e-8dc3-4608-8547-36c14c79e1f6/concepts/1b28036b-e9b2-4a8a-9f92-b613f5542f90

Last option in quiz says: 
"Middleware like logger can be considered as a third-party extension point between dispatching an action and having that action reaches the reducer" -should be reach?

Ticket #648422

**Comment by hbkwong** [comment]
Fixed! @JessicaBettencourt

**Comment by JessicaBettencourt** [comment]
Thank you!
