### ISSUE TITLE
Blurb: "Short-circuit Evaluation Syntax" should be moved to earlier lesson.

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#226]
Blurb explaining the use of Short Circuit Evaluation syntax for Conditionally Rendering JSX, should be relocated to the module that *first* uses the technique.

The blurb on its use is Great.  
However, We Already used Short Circuit Evaluation to Conditionally Render JSX earlier in the course.

"Short-circuit Evaluation Syntax"..

Should be relocated to:
- Core 2: React Fundamentals, Lesson 3: State Management, Module: 7. Controlled Components, Video 5: Showing The Displayed Contacts Count
-  commit:  
https://github.com/udacity/reactnd-contacts-complete/commit/1ca08610c76a33da761b6d85e303cd8c436519de#diff-c3832dc2f1b1027b83ef9ef8628376cb

Currently located at:  
- Core 2: React Fundamentals, Lesson 5: Managing App Location with React Router, Module: 2. Dynamically Render Pages,  Video 1.
- Section to relocate is titled: "Short-circuit Evaluation Syntax", located under video 1.
- commit: https://github.com/udacity/reactnd-contacts-complete/commit/db0aafdc7766048c28597d37f31977ac7833a62e

Obviously the code referenced in the blurb would need to be updated to reflect the content of this earlier commit.

**Comment by hbkwong** [comment]
This one as well!
