### ISSUE TITLE
move onCreateContact() call in CreateContact.js to video 2

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#228]
`if (this.props.onCreateContact) {      
  this.props.onCreateContact(values)
}`
in `CreateContacts.js`'s `handleSubmit()` method

from:  
Lesson 5, 
module 6. Finish the Contact Form
video 2

from commit:  
https://github.com/udacity/reactnd-contacts-complete/commit/554bab12367719b1526900ea27b8bb60237aba0d

Would be better placed in :  
Lesson 5, 
module 6. Finish the Contact Form
video 3

in commit
https://github.com/udacity/reactnd-contacts-complete/commit/6ea0a9abe23c06465447bc2b0366e6c794eaefbf

where the `onCreateContact` prop, and the `createContact` method on App are created and written.

This should be a "contextual" lesson, not a "complete this file" lesson.

As is, it's completely out of context, was thrown in at the last minute, and in fact does nothing.   
The video leaves the mysteriously function unexplained, and us (me) puzzled.  In fact, I searched both my code, and all src files of this commit to find any reference to 'onCreateContact' to no avail.  

.. or (second choice): add a comment to the video stating that createContact() will be created in the next video and passed in as onCreateContact prop, and indicate what it will do.
Better to just cut out that last 1 minute of video, and add it to the next.

Moving that line of code to the following video, and following commit, adheres to the "do 1 thing" principle, keeping createContact/onCreateContact code all in one commit, and one video,  providing a contextually complete lesson/topic/video/commit.  

.. and removes any would be confusion about the code.

**Comment by hbkwong** [comment]
This one as well!
