### ISSUE TITLE
add blurb on usage of { history } prop, history.push()

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#229]
Please add a Blurb giving Context explaining where `history` prop comes from, why we are able to "pull it out of thin air" into our `Route`'s `render()` property/method, what `history.push()` does, and why this causes our app to re-render at the supplied URL.  

Even a statement pointing out that while '<Link to="sampleURL">' provides user-initiated navigation, `history.push("/sampleURL")` gives us a way to programatically change the URL ("navigate") from within the app.

`history`, and `history.push()` were thrown in here:

- Core 2: React Fundamentals, Lesson 5: Managing App Location with React Router, Module: 6. Finishing the Contact Form,  Video 3: Update Server With New Contact  

- commit: https://github.com/udacity/reactnd-contacts-complete/commit/6ea0a9abe23c06465447bc2b0366e6c794eaefbf

A brief blurb beneath this video would wipe away confusion, enhance understanding, and jumpstart our own research into its usage.

**Comment by hbkwong** [comment]
This one as well!
