### ISSUE TITLE
PropTypes should be added to CreateContact Component

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#230]
Core 2: React Fundamentals,  
Lesson 5: Managing App Location with React Router,   
Module: 6. Finishing The Contact Form
Video 3:  Update Server With New Contact
commit:  https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/3a472639-ed92-4293-897f-ff8b698030b2/concepts/c0ac3de9-54e5-46ce-ae94-aedfc1677632

App.js  `<Route>` component that renders `<CreateContact>`   
  is refactored to pass in props (namely `onCreateContact`).   

CreateContact.js should add a corresponding PropTypes check for `props.onCreateContact`  

`import PropTypes from 'prop-types'`, and 
```
Class CreateContact extends Component {
  static propTypes = {
    contacts: PropTypes.array.isRequired,
    onDeleteContact: PropTypes.func.isRequired,
  }
  ...
}

```
Or, if CreateContact is refactored to be a Stateless Functional Component (as I think it ought)  
```
CreateContact.propTypes = {
  onCreateContact: PropTypes.func.isRequired
};
```

**Comment by SherylHohman** [comment]
Also, if PropTypes is used, perhaps this line of code could be removed:  
`   if (props.onCreateContact) { `
ie: 
```
   if (props.onCreateContact) {
      // call this function, giving it our new contact's data to process (calls API..)
      props.onCreateContact(formData);
    }
 ```
simplified to:  
`props.onCreateContact(formData);`

What are your thoughts on best practices: is still a good idea keep this line for error checking ?  

Personally, I think a more useful error check, would be to make sure all <input> fields were not empty strings before submitting to DB.  During testing I added empty contacts, which didn't break the app, but React ListContacts render method Warned that that element didn't have a proper key.  Indeed, that contact had only a single property: `{error: "Please provide both a name and email address"}

Of course, that check isn't really necessary at this time, and I'm sure input validation will be a later part of the course.  We're more likely to run across this error than a missing onCreateContact prop at this point.  Especiallly if PropTypes is added.  
.. and the call to onCreateContact is moved to the following video/commit, where the prop is actually created and passed in.

**Comment by hbkwong** [comment]
Hey Sheryl, thanks for the heads up on this. This is incredibly detailed, and we appreciate it. 

Again, we're in the process of making some updates to the React Nanodegree program. Keeping this one on the board for a future release!
