### ISSUE TITLE
minor typo, missing tword "to" in C3,L1,M3

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#231]
is:  
`..and what sole entity is allowed trigger an update (an action) to that state.`

should be:  
`..and what sole entity is allowed to trigger an update (an action) to that state.`

Missing:  
the word `to`.

Core 3: Redux
Lesson 1: Why Redux
Module 3: How Redux Improves Predictibility
heading Predictibility

**Comment by hbkwong** [comment]
Fixed! Thanks for being incredibly detailed in your posts, Sheryl. Hope you had a wonderful weekend!
