### ISSUE TITLE
Task Checklist Item: Controlled Component? or UnControlled ?

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#232]
I believe the "quiz" Checklist at the bottom of the page should be asking if our input form is UnControlled, rather than Controlled.  
(..when coded according to the video/commit)   

Core 3: React and Redux  
Lesson 2: Redux At Its Core  
Module 5: All Together Now!  
Classroom Link:   https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/782f801d-3bd8-4b2b-b788-608b0fbe1306/concepts/6760be57-eed3-4f4b-b307-87c3477517ba  
Section: Checklist ("quiz") near the bottom of the page.   
Commit: https://github.com/udacity/reactnd-udacimeals-complete/commit/d0d4b8ade3dea46b7a3250ea196e0f862a399672  

According to my understanding, we created an UNcontrolled input form, not a Controlled one.  

1) There is no state for (value of) the input field in this component  
2) We are using "ref", which is (I think) read only  
3) This looks just like pattern given the example for Uncontrolled Components in the React docs:   https://reactjs.org/docs/uncontrolled-components.html  

The checklist at the bottom of this lesson asks that we created a Controlled Component.  
I believe that it should be asking if we created an UnControlled Component.  

Though I would be happy to do either.  

Am I missing something?  
Or misunderstanding the distinction between the tow? 
Does connecting this to redux, somehow make it controlled?  

Please correct me if I misunderstand !  
Thx. :-)

**Comment by hbkwong** [comment]
Great catch! The docs show it quite clearly, and isn't too far from the approach we took in the project as well. Thank you as always for your contributions, Sheryl!
