### ISSUE TITLE
Udacimeals - show us sample data before starting

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#235]
Seeing what the data would eventually look like would be Super helpful.  Reverse engineering the code to glean an inside to how the data was going to be stored, so that we could code to store the data, is a bit counter productive.  And was not even fully possible, until *after* the project was Finished!  

Even better, include sample starting data, like you do in our api servers.

Also, many times, an app will have a couple sample items already filled in, when the app is downloaded.  This gives the user a chance to see what the app looks like, rather than a blank screen, and somewhere to start.  It's usually something simple and easily deleted.

I did this (parts were slightly incorrect, because it was impossible to get it correct until completed), but it was awesome, particularly when it came time to code the calendar UI, and I had data to see a) what it looked like, b) that it was working.
Unfortunately, I could only do this up to a certain section.  After that I *had* to rely on copy/paste, rather than try to do in "on my own" with a safety net of your code repo.

I'll post sample data, and update these waffle's with lesson details, etc once I "finish"  Project 2. I made a bunch of notes to sit down and do this properly.  Since I'm here, I wanted to thrown down this rough draft.  

I think this is one of the major improvements that could be made to the React-Redux code-along lesson.

**Comment by hbkwong** [comment]
Hey Sheryl, thanks again for the detailed description here! We're making some updates to the React ND program, and we'll make sure this is addressed. Stay tuned!
