### ISSUE TITLE
Code-along for react-redux, core 3 Suggestion

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#236]
The other Major suggestion for Core 3 is, if that code-along were a "refactor" from react to react-redux -- that would be fantastic!  
I think we'd really see how the workings of redux worked, and gain insight on benefits/drawbacks, strengths/weaknesses of each, and when we might choose one vs the other.  Also, on an app that we are already familiar with, and already have the UI cessed out, we can focus on learning redux, rather than trying to figure out the data-structure, just what the app is supposed to be doing, and copy-pasting in UI.  Just a thought, but I think that could make a great deep-dive into redux.

Honestly, my Reader app I think was a better candidate for redux than UdaciMeals.  In Reader, I had data shared across components, requiring me to move that data up higher than it otherwise "should have been".  I also had to deeply pass functions and data through several layers on "intermediary" components that really had no use for them.  As I was coding this, I kinda felt it was awkward to do so.  Not for all the data/methods, but some, certainly.
What a *great* intro for redux.  If only refactoring *that* app was the redux lesson..! 
(That wouldn't be practical obviously, because everyone wrote a different version of the app).  But if, say Contacts, was written to have some of these features begging for redux, than *that* would be an awesome app for the redux lesson.  Continue on with the same app, refactor and learn redux. Leave out the busy work associated with udacimeals. And do a deep dive that really shines on (comparative) features of redux.  We could learn react without redux better, And redux better in the process.
My opinion, of course.

**Comment by hbkwong** [comment]
Hey Sheryl, thanks again for the insight on this one! We made a ton of improvements to the second course (React & Redux) for the React Nanodegree program, much of which involve refactoring a more "naive" implementation of an app.
