### ISSUE TITLE
Pure Function example is not pure

### ISSUE THREAD

**Issue by YoungsAppWorkshop** [udacity/reactnd-issues#237]

**Comment by YoungsAppWorkshop** [comment]
Module 3. React & Redux > 1. Why Redux? > 5. Pure Functions

In the video of the pure functions examples, `pureSquareItems` function, which isn't a pure function, is introduced as a pure function. As you can see the below, the `pureSquareItems` function depends on the `square` function which is outside of the `pureSquareItems` function. The `square` function should be passed as an argument to make  the `pureSquareItems` pure. It is found by @muhammad-saleh, but I'm reporting this for convenience.

// Code example from the video
function square(n) {
    return n * n;
}

function pureSquareItems(arr) {
    return arr.map(square);
}

// Alternative example
function pureSquareItems(arr, func = square) {
    return arr.map(func);
}

**Comment by hbkwong** [comment]
Hey @YoungsAppWorkshop, thanks for checking in. And good catch -- a pure function should absolutely _not_ depend on external state. We're making some big updates/additions for the next version of this course, so stay tuned!
