### ISSUE TITLE
minor CC problem

### ISSUE THREAD

**Issue by kratam** [udacity/reactnd-issues#238]
There's a small error in Native Features / Local Notifications (see the image in the comment)

**Comment by kratam** [comment]
![reactnd-typo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6dffde86e099001450bd65/125516c66e82c728ace21e0d46fa919b20968dadc2fda653ab1fbcd6395428792c07b7692ac7b671eb1a2b040e0d1aa5175a5946fcf9df2cafb33e758e5519f1c32f0e2a92624cf5f2d75dad0ba821824584b3bd8d4dc5e03827e583884e2c53.png)

**Comment by hbkwong** [comment]
Fixed! I created a pull request on that subtitle file in question. The change should be live within the next day or two. Thanks @kratam
