### ISSUE TITLE
Rubrics: push notification should be local notification

### ISSUE THREAD

**Issue by kratam** [udacity/reactnd-issues#239]
The [rubrics](https://review.udacity.com/#!/rubrics/1021/view) says:

> Does the user receive a push notification at a particular time if they haven't studied that day?
Logic for push notification has been implemented. Push notifications are generated at a specific time if the user hasn't completed at least one quiz for that day.

Based on the course I think the requirement is to add local notifications instead:

> When dealing with notifications, it's important to understand that there are two different types: push notifications, and local notifications.

**Comment by hbkwong** [comment]
Good call @kratam. Based on the curriculum (and just the nature of this project), a _push_ notification isn't required. I'm removing all instances of it in the rubric. Thanks for reporting this!
