### ISSUE TITLE
Lesson 2.5 - 24 - UI Rendering Outro

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#24]
The number 24 doesn't look like it belongs in 24 - UI Rendering Outro heading.

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/3bb3c78a-196b-4ac0-ac38-a6ab92015fcb

**Comment by hbkwong** [comment]
Looks like this was since fixed too. Thank you Kelli!
