### ISSUE TITLE
Color of answers on quizzes

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#240]
This is not something that can be fixed immediately, but a student suggested that answers to quizzes should be in a different color than red. Even when they get the answer right, the red font makes them immediately think that they got the answer wrong. 

Ticket #701485

**Comment by hbkwong** [comment]
@JessicaBettencourt Does the student mean the choices to checkbox quizzes? For better or for worse, red is the color of code markdown (`like this`) in Coco :\

**Comment by JessicaBettencourt** [comment]
Ahh makes sense. They are referring to the code markdown. Thanks for clarifying!

**Comment by hbkwong** [comment]
No prob! Good feedback though

**Comment by SherylHohman** [comment]
Thanks!  I made that suggestion!  I would *love* to see the "Things you got right" to have green-color coding for the `code`, and the parts that were wrong to have red.
Even though I "know better" by now, My brain immediately sees red: everything is marked as wrong.  As it stands, it takes two takes to correctly process the feedback.
