### ISSUE TITLE
Readable Project possible api bug

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#241]
In function app.post, const {option} is passed to posts.vote as an object. However, posts.vote expects a string: 
//////////////////////////// 
app.post('/posts/:id', bodyParser.json(), (req, res) => { 
const { option } = req.body 
const id = req.params.id 
posts.vote(req.token, id, option) 
.then( 
(data) => res.send(data), 
(error) => { 
console.error(error) 
res.status(500).send({ 
error: 'There was an error.' 
}) 
} 
) 
}) 
////////////////////////////// 
function vote (token, id, option) { 
return new Promise((res) => { 
let posts = getData(token) 
post = posts[id] 
switch(option) { 
case "upVote": 
post.voteScore = post.voteScore + 1 
break 
case "downVote": 
post.voteScore = post.voteScore - 1 
break 
default: 
console.log(`posts.vote received incorrect parameter: ${option}`) 
} 
res(post) 
}) 
} 
//////////////////////////////////// 
Changing app.post to the following works (otherwise exceptions thrown in app.post (if a string, instead of an object, is passed through api call) or in posts.vote (since the object is passed):

app.post('/posts/:id', bodyParser.json(), (req, res) => { 
const option = JSON.stringify(req.body) 
obj = JSON.parse(option); 
posts.vote(req.token, req.params.id, obj.vote) 
.then( 
(data) => res.send(data), 
(error) => { 
console.error(error) 
res.status(500).send({ 
error: 'There was an error.' 
}) 
} 
) 
})

Ticket #707125

**Comment by veronikabenkeser** [comment]
Not a bug since `curl  -H "Authorization: hello" -H "Accept: application/json"  -H "Content-Type: application/json"  -X POST -d '{"option":"upVote"}' http://localhost:5001/posts/1`  works.
