### ISSUE TITLE
Defaults and Destructing Clarification

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#242]
https://classroom.udacity.com/nanodegrees/nd019/parts/290ec447-6555-41bf-ac39-457220a09aae/modules/9c5b7af0-0943-4d6e-b672-520440885aba/lessons/3925704a-be38-4b70-8c8b-a4a812b6a309/concepts/5368e2c8-157b-4c15-8aa8-e06a699e9798#

For this page in the ES6 course, I suggest also pointing out that we can simply use a comma before the second array index.

createSundae([undefined, ['Hot Fudge', 'Sprinkles', 'Caramel']]); 
createSundae([, ['Hot Fudge', 'Sprinkles', 'Caramel']]); 
Both of these statements return the same output.

Ticket #709639

**Comment by veronikabenkeser** [comment]
This is not a common practice; it's better to include "undefined" to avoid bugs.
