### ISSUE TITLE
Built-ins

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#243]
https://classroom.udacity.com/nanodegrees/nd019/parts/290ec447-6555-41bf-ac39-457220a09aae/modules/9c5b7af0-0943-4d6e-b672-520440885aba/lessons/1b997dce-e2ce-4246-b5ae-d39ca175f887/concepts/e221c233-0e17-4b16-8aba-c42212c33250

To generate that output here they should switch key, value in the arguments as in:

members.forEach((value, key) => console.log(key, value)); 
forEach() takes first argument as the value, second for key.

Ticket #709639

**Comment by veronikabenkeser** [comment]
Thank you, Jessica! Fixed.
