### ISSUE TITLE
The URL for Firesheep is incorrect

### ISSUE THREAD

**Issue by czeise** [udacity/reactnd-issues#246]
In the [Securing HTTP section](https://classroom.udacity.com/nanodegrees/nd019/parts/a6fb0c7c-5ae4-4c2f-95b3-64052a6b825e/modules/2ade007c-9ac6-4dad-995d-6dec0deb7c8f/lessons/8150909334/concepts/82548188640923) of the HTTPS Lesson, the URL for Firesheep is incorrect.

Incorrect URL provided: http://codebutler.com/firesheep/

Correct URL: http://codebutler.com/firesheep

**Comment by hbkwong** [comment]
Fixed! Thanks for repoting, @czeise
