### ISSUE TITLE
Lessin 5 Part 6 - Missing component file

### ISSUE THREAD

**Issue by ghoshabhi** [udacity/reactnd-issues#25]
There's a component called <ImageInput /> used in this lesson, but I am not sure if this is covered in any lessons before this one.

https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/3a472639-ed92-4293-897f-ff8b698030b2/concepts/c0ac3de9-54e5-46ce-ae94-aedfc1677632

**Comment by forbiddenvoid** [comment]
Which component?

**Comment by asparr** [comment]
@ghoshabhi I couldn't find a component called  "used" in any of the videos on the link you provided. could you provide a time stamp? a screenshot?

**Comment by forbiddenvoid** [comment]
ImageInput.js

**Comment by ghoshabhi** [comment]
I am really sorry everyone!
