### ISSUE TITLE
extra line after answer makes answer look wrong.

### ISSUE THREAD

**Issue by fmd123** [udacity/reactnd-issues#250]
I gave correct answer: 
{props.items}
but because I had an extra line below it (which of course I couldn't see!) the answer was marked as incorrect.

**Comment by hbkwong** [comment]
Hey @fmd123, thanks for reporting! Can you link to the exact quiz in question? I'll check out what's going on

**Comment by fmd123** [comment]
Thanks for your reply.

https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/0be66a50-3b7d-4029-9d3e-7a9b52c6063c

This is the second question in Functional Components.

If you hit return after typing {props.items} it counts it as wrong. It also
doesn't like a space after the answer. I'm passing the quiz now when I
remove the return


You can see where my cursor is in the screen shot.

**Comment by hbkwong** [comment]
Thanks @fmd123. I fixed up the regex behind the scenes. Now the newline shouldn't affect the outcome!

**Comment by fmd123** [comment]
:-)
