### ISSUE TITLE
Broken Link V1 Normalizing State Shape

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/reactnd-issues#251]
https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/de8a0fcf-1da3-48ae-912b-1189d6851335/concepts/a8a1152f-fa4f-4434-87cc-818adf69315c

https://redux.js.org/docs/recipes/reducers/NormalizingStateShape

"Page not found"

**Comment by hbkwong** [comment]
Fixed! Thank you for reporting, @JessicaBettencourt
