### ISSUE TITLE
Wrong Link in Redux At Its Core Lesson

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/reactnd-issues#252]
Redux Basics basics link provided at the bottom on [this](https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/782f801d-3bd8-4b2b-b788-608b0fbe1306/concepts/526e0d73-cc7c-4bc6-a43b-568679a1381b) page (React & Redux => Lesson 2: Redux At Its Core => 6. Lesson Summary) link to wrong page.

The correct URL is : https://redux.js.org/basics
Currently it links to: https://redux.js.org/docs/basics/

**Comment by richardkalehoff** [comment]
Thanks for the feedback, just fixed this!
