### ISSUE TITLE
incorrect instruction to create Udacimeals project under Redux - Lesson 2

### ISSUE THREAD

**Issue by BhavikCpatel** [udacity/reactnd-issues#254]
the following instructions should be updated to use "udacimeals" instead of "Udacimeals" as create-react-app gives error when we have capital letters (See error message below)

> ** I have used create-react-app to create the Udacimeals project **

Could not create a project called "Udacimeals" because of npm naming restrictions:
  *  name can no longer contain capital letters

**Comment by veronikabenkeser** [comment]
Thank you for flagging this. Fixed.
