### ISSUE TITLE
Lesson 3 Part 2: hardcoded array does not match provided reactnd-contacts-server

### ISSUE THREAD

**Issue by anall** [udacity/reactnd-issues#259]
The hardcoded contacts array wants "karen.jpg", "richard.jpg", and "tyler.jpg" -- while the reactnd-contacts-server git repo has "michael.jpg", "ryan.jpg", and "tyler.jpg"

**Comment by alqahtani** [comment]
after the last commit ([47501be](https://github.com/udacity/reactnd-contacts-server/commit/47501be033ce838c49c1f8e7af64334db170a514)) now the server has "city.jpg", "trees.jpg" and "tyler.jpg"

**Comment by veronikabenkeser** [comment]
Thank you for flagging this! The server code has been updated and now lives in this repo: https://github.com/udacity/reactnd-contacts-server2.
