### ISSUE TITLE
Optional features are said to be "required"

### ISSUE THREAD

**Issue by ghoshabhi** [udacity/reactnd-issues#26]
Richard, in this video: https://youtu.be/IAgJx38-nRI?t=28 : [Lesson: Above and Beyond](https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/1c3110e6-46f7-4929-8cf4-8332afbbaadf/lessons/5d31386c-8c1c-4f32-974d-6bf3c1062cba/concepts/ebe15bca-790a-450e-b35d-db202599d753) says:

"... these are *required*, but they will definitely push you to learn React"

and what I think he wanted to say is: "... these are *not* required..." because they are anyways not required as per the rubric.

Or even if they are required, it is said in a tone which sounds like it is not required.

**Comment by forbiddenvoid** [comment]
Abhi, he actually says they "aren't" required.

**Comment by ghoshabhi** [comment]
Really sorry!
