### ISSUE TITLE
4.2.2 update these links (correct urls provided)

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#264]
https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/4df595e8-bd65-435e-ad88-0db5d27c44a2/concepts/ce1bfe1d-dd63-4711-bc3f-aab263075d98

Links should be updated to the following:

[navigation bar](https://developer.apple.com/ios/human-interface-guidelines/bars/navigation-bars/)

[tab bars](https://developer.apple.com/ios/human-interface-guidelines/bars/tab-bars/)

------------
Also, the intro to this link (interface essentials) conveys your point well - perhaps add this link, or replace one of the 3 ios links with this one:
https://developer.apple.com/ios/human-interface-guidelines/overview/interface-essentials/

**Comment by veronikabenkeser** [comment]
Thank you for proving the updated links and a great suggestion! Done.
