### ISSUE TITLE
code in C4.L1.S3 causes errors when we first use it in C4.L2.S3

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#265]
Core4 Lesson1 Segment3 has us paste in the 'utils/helpers.js' code.
But the code we paste in causes an error when we use it in Core4.Lesson3.Section3.

The code provided relies on an import (styles) that we do not have (yet), causing an error for us to debug. It also differs from the video, and the state of our app on other ways. 
(For one, even the video states that though the color will later be changed to white, we define it as `black` for now.  Otherwise we will not be able to see the icons them against the white background.  How can we know if our app is working, if the icons are invisible.

Essentially the code shown is for a later stage in the app, not the starting stage.

Here is what the file should look like when it is initially created:  

```
import React from 'react'
import { View } from 'react-native'
import { FontAwesome, MaterialIcons, MaterialCommunityIcons } from '@expo/vector-icons'
import { white } from './colors'

export function getMetricMetaInfo (metric) {
  const info = {
    run: {
      displayName: 'Run',
      max: 50,
      unit: 'miles',
      step: 1,
      type: 'steppers',
      getIcon() {
        return (
          <View>
            <MaterialIcons
              name='directions-run'
              color={'black'}
              size={35}
            />
          </View>
        )
      }
    },
    bike: {
      displayName: 'Bike',
      max: 100,
      unit: 'miles',
      step: 1,
      type: 'steppers',
      getIcon() {
        return (
          <View>
            <MaterialCommunityIcons
              name='bike'
              color={'black'}
              size={32}
            />
          </View>
        )
      }
    },
    swim: {
      displayName: 'Swim',
      max: 9900,
      unit: 'meters',
      step: 100,
      type: 'steppers',
      getIcon() {
        return (
          <View>
            <MaterialCommunityIcons
              name='swim'
              color={'black'}
              size={35}
            />
          </View>
        )
      }
    },
    sleep: {
      displayName: 'Sleep',
      max: 24,
      unit: 'hours',
      step: 1,
      type: 'slider',
      getIcon() {
        return (
          <View>
            <FontAwesome
              name='bed'
              color={'black'}
              size={30}
            />
          </View>
        )
      }
    },
    eat: {
      displayName: 'Eat',
      max: 10,
      unit: 'rating',
      step: 1,
      type: 'slider',
      getIcon() {
        return (
          <View>
            <MaterialCommunityIcons
              name='food'
              color={'black'}
              size={35}
            />
          </View>
        )
      }
    },
  }

  return typeof metric === 'undefined'
    ? info
    : info[metric]
}

export function isBetween (num, x, y) {
  if (num >= x && num <= y) {
    return true
  }

  return false
}

export function calculateDirection (heading) {
  let direction = ''

  if (isBetween(heading, 0, 22.5)) {
    direction = 'North'
  } else if (isBetween(heading, 22.5, 67.5)) {
    direction = 'North East'
  } else if (isBetween(heading, 67.5, 112.5)) {
    direction = 'East'
  } else if (isBetween(heading, 112.5, 157.5)) {
    direction = 'South East'
  } else if (isBetween(heading, 157.5, 202.5)) {
    direction = 'South'
  } else if (isBetween(heading, 202.5, 247.5)) {
    direction = 'South West'
  } else if (isBetween(heading, 247.5, 292.5)) {
    direction = 'West'
  } else if (isBetween(heading, 292.5, 337.5)) {
    direction = 'North West'
  } else if (isBetween(heading, 337.5, 360)) {
    direction = 'North'
  } else {
    direction = 'Calculating'
  }

  return direction
}

export function timeToString (time = Date.now()) {
  const date = new Date(time)
  const todayUTC = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()))
  return todayUTC.toISOString().split('T')[0]
}
```

[In Lesson 2, Section 3](https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/4df595e8-bd65-435e-ad88-0db5d27c44a2/concepts/d589fc03-638e-4f72-b6cb-1cbf22c9bf3f) we have [ our "first" coding commit](https://github.com/udacity/reactnd-UdaciFitness-complete/commit/aa767680f50fb26e7e8201fd6a664dfd49f50ac9):
 -  `styles` is undefined, and we have not been introduced to them, so having them in the file produces a compilation error.

- At this point in our app, the background color is `white`, so, as in the accompaning video, we need the icons to be white right now as well.

- I suppose the `import`s *could* be left as part of the exercise, but since we are not otherwise touching *this* file right now, there is no point.
Simply creating the component that uses the helper file, and updating App.js seems to be the appropriate (and probably intended) bits we would be programming in this commit/section/lesson-bit.

The other option would be to include all the imports, including the style, and the style file, and change the starting point of the app to have a black background.

A less ideal solution.

Either way, every student should not need to be trouble shooting these bugs.  We make *plenty* on our own ;-)
We just need to start with an "earlier" version of `helpers.js`.

**Comment by veronikabenkeser** [comment]
Thank you for your feedback, Sheryl! I really appreciate the amount of detail you included in your waffle tickets - thank you! Fixed.
