### ISSUE TITLE
Workspace for readable missing PR#21

### ISSUE THREAD

**Issue by ianbarnett8** [udacity/reactnd-issues#266]
I'm working on my workspace for the readable project but the GET /posts requests does not return the comment count. Seems that PR#21 has not been applied to the workspace. https://github.com/udacity/reactnd-project-readable-starter/pull/21/files.

Also might there be other PRs not applied to the workspace?

**Comment by veronikabenkeser** [comment]
Thank you for flagging this. Fixed.
