### ISSUE TITLE
C4.L2.S3.Touchables: 2 components missing from list of items discussed in video

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#267]
https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/4df595e8-bd65-435e-ad88-0db5d27c44a2/concepts/d589fc03-638e-4f72-b6cb-1cbf22c9bf3f#

"Touchables" section lists only 3 of the 5 "touchables" covered in the video.

The 2 missing items are:   
- `TouchableNativeFeedback`   
- `TouchableWithoutFeedback` 

Please add for easy reference, and completeness.

**Comment by veronikabenkeser** [comment]
Thank you for flagging this! Fixed.
