### ISSUE TITLE
C4.L2.S3 Please add branch title for commit links/videos

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#268]
https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/4df595e8-bd65-435e-ad88-0db5d27c44a2/concepts/d589fc03-638e-4f72-b6cb-1cbf22c9bf3f#

Please label the Commit Links and/or related videos with the name of the commit branch.

As is, when we need to go back and check a video or a commit for something, we mus blindly click through all commit links or blindly start playing each video one-by-on until we find the one we need.

There are so many videos and links just popped in there back to back, all unlabeled, and with little to no text  to place them in context, that it is difficult to use this lesson page as a reference when we run into an issue.

Sometimes a question we have, or an issue we run into does no surface until later.
Without Labels, it is unnecessarily cumbersome to revisit any topic (video or code).

Simple/Minimal Solution:
Clicking on the Commit link, brings up the window for that commit (Duh). At the head of that commit is the commit message, or Branch Name for that commit.

For example:  
`Changes for AddEntry-TextButton`   

Could be added to the link for this commit:   
https://github.com/udacity/reactnd-UdaciFitness-complete/commit/1faffa1c2df4775c3f4fb1dc7460faca86b084fe

Simply copying that label and adding it as text for (or above) the link would ***Greatly*** Improve our ability to use these resources !

**Comment by armujahid** [comment]
Exactly, instead of using commit links. reactnd should use branches with relavent names so that we can easily switch and play with code at any state. This has already been done in other courses of Udacity.

**Comment by veronikabenkeser** [comment]
Hi @SherylHohman and @armujahid, thank you for your suggestions! We tried giving all of the commits descriptive names to make it easier for students to map the content to the commits. We'll definitely consider implementing your suggestions in the future iterations of the program!
