### ISSUE TITLE
Lesson 3.1 Checklist

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#27]
The third item in the checklist says "create api folder in utils/ContactsAPI.js" but you can't create a folder inside a file.

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/38cbfc18-d355-4297-b45b-db449cb92425

**Comment by kellim** [comment]
It would also be nice for the checklist to go into more detail and provide links to download files  (like the contact list and the api, and even an updated index.css) rather than having to get all the information on how to update your file from a github commit.

Also, in the 5th item in the checklist, it would be helpful to replace the word "stuff" to be "files" so you know you are to delete the whole file as it looks like you totally delete the App.css and Logo.svg files.

And as for the last item in the checklist, it would be nice to have more details like what file(s) you are deleting the references from.

I think a video walking you through all of this customization of the create-react-app project would be helpful.

**Comment by kellim** [comment]
The 4th item in the checklist says "paste content into the ContactsAPI.js file" but you are also creating that file and this makes it sound like you already have a ContactsAPI.js file.

**Comment by richardkalehoff** [comment]
Thanks for this awesome feedback! I've completely revamped this checklist!
