### ISSUE TITLE
C4.L2.S4 text incorrectly indicates that a method was covered in the lesson.

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#270]
https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/4df595e8-bd65-435e-ad88-0db5d27c44a2/concepts/860caf55-6839-4775-b0cb-f3bc201e4a2f#

At bottom of page, there is list item indicating that we went over a `clear` method.

.. but I don't thing `clear` was covered anywhere.  Forgive, if I somehow just "missed" it.

**Comment by SherylHohman** [comment]
(suggestion: remove `clear` from the list)

**Comment by veronikabenkeser** [comment]
Thank you for flagging this! Fixed.
