### ISSUE TITLE
C4.L3.S2 remove erroneous text

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#272]
https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/0d761c28-fb21-432e-a822-f9495ec1b64b/concepts/902ff149-3220-492a-8dde-e858801d26df#

`But as we mentioned above, using StyleSheet...`

should be: `But, using StyleSheet...`
as the performance benefit was *not* mentioned above - rather, that is the answer to the question burning in our heads right now!

**Comment by hbkwong** [comment]
Fixed! Thanks Sheryl
