### ISSUE TITLE
C4.L3.S2 typo

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#274]
Typo in the following quote:

`It also allows to send the style only once through the bridge. All subsequent uses are going to refer an id (not implemented yet).`

Has a typo: missing the word `to`.

Since this is a quote, perhaps this typo is in the docs ? If not, I suggest fixing to:

`It also allows to send the style only once through the bridge. All subsequent uses are going to refer  to an id (not implemented yet).`

**Comment by veronikabenkeser** [comment]
Thank you for flagging! Fixed.
