### ISSUE TITLE
C4.L3.S2 incorrect quiz item

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#275]

**Comment by SherylHohman** [comment]
What is true about styling in React Native?

 ` Using CSS in JS gives us access to application state or props in the component`

The above line is required to be checked to pass the quiz.

How can that be ??
CSS is not the provider of state or props !!  I can write a whole app with no CSS whatsoever.
(ugly, but possible).

I'm entirely unclear what is intended by that line. Can it be: 
 - re-written for clarity, or
-  removed as part of the "correct" answer

**Comment by veronikabenkeser** [comment]
Hi Sheryl, thank you so much for flagging this! We've modified the quiz in the classroom.
