### ISSUE TITLE
C4.L3.P3 Flexbox Guide

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#276]
Love that you put a table of contents!

Is this something you are thinking of rolling out for other Lesson Pages as well ?

I would particularly to see something like that for 
C4.L2.Page/Part 2 or 3.  
One of those lesson Pages had Quite a Number of Videos, but no headings, or labels for the Videos or Commits.  
A TOC (or Headings or Labels, breaking the Page into Sections) would be helpful when re-visiting topics !!

**Comment by veronikabenkeser** [comment]
Thank you for your feedback, Sheryl! I'll pass it on to the team.
