### ISSUE TITLE
C4.L3.P4 typo in quiz

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#277]
Quiz Item:
`React Native properties are written in camelCase.`

Should be:   
`In React Native, CSS properties are written in camelCase.`

https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/0d761c28-fb21-432e-a822-f9495ec1b64b/concepts/7e4227ed-4b7b-45bb-8cb3-bb8fe44a65ed#

**Comment by hbkwong** [comment]
The suggestion is much clearer. Fixed! Thanks again, Sheryl
