### ISSUE TITLE
C4.L3.P4 edit text suggestion.

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#279]
C4.L3.P4

`React Native uses flexbox to manage layout in mobile applications. However, there are some minor distinctions between the official flexbox specification (i.e., CSS on the web) and React Native's own implementation. Most of these distinctions are just differences in default settings.

Since differences also exist in how Android and iOS applications should look and feel, React Native also offers a Platform API to do just that.`

Notice that ` to do just that`, does not exactly make sense here, grammatically.

Suggestion: re- word that final sentence.
One option:  
`..React Native also offers a Platform API, which we can use to style each platform independently.`

[url of classroom Page: ](https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/0d761c28-fb21-432e-a822-f9495ec1b64b/concepts/7e4227ed-4b7b-45bb-8cb3-bb8fe44a65ed#)

**Comment by hbkwong** [comment]
Great catch, Sheryl. "... do just that" sounds fine -- but it doesn't really refer to anything here. It's since been fixed!
