### ISSUE TITLE
Lesson 3.2 - second video - missing a previous video?

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#28]
The second video says "we created our icons and our utils folder from a previous video" However, there is currently no previous video that showed creating the icons and utils folder. There was just a link to a GitHub commit in the previous lesson that you had to match your code to.

**Comment by kellim** [comment]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/6bc1e32e-089d-43ec-aef4-f83b9f7d37cc

**Comment by forbiddenvoid** [comment]
Fixed!
