### ISSUE TITLE
C4.L3.P4 please add commit/video titles

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#281]
Also, please add the command we need for installing the calendar data to the text body, beneath the video/commit, so we do not need to scrub through the video to find it.

`yarn add udacifitness-calendar`

Labeling the Commit link with a brief description of what was covered in the video, or at minimum, the branch name, OR adding a brief text description below the video OR a  Header/Title above the video would go a long way in making this material more suitable as a workbook or study guide or make it more text-book like so we can easily reference the sections of code or re-watch videos as necessary.

As it is, we blindly click on videos, watching bits of each until we find the one we need to re-visit.
Same for the commits.  If we run into a problem and need to check one of the commits, again we blindly open successive commit diffs, and scan them until we happen to click on the one we need.

Many of the Pages in Core 4 would benefit from the is addition. !!

Thanks.

----------------------

Content is Excellent.  
Layout is good.  
A few UI details would elevate the classroom format>
As is, it is best suitable for one 1-time consumption-only format (watch/read and move on).  

But Udacity Courses are not designed to be a "Spectator Sport".
A few UI details would elevate the materials to be more participatory in nature. 
Friendly for:
immersive coding, studying, and reference.
Particularly when we try to do the work on our own, re-referencing materials only as needed.  Often we need to check something out from  a couple commits/videos ago.

Also whenever we re-fresh a page (or return on a later day, our "location" in the the video/commit list is GONE.

Again, without titles/descriptions, we currently need to "randomly" click on various videos to find the one we left off at..

Small details, make a huge difference for students !  And fortunately, you have many, many students.  So the impact of these details adds up to a ton of (student) man hours (saved), a more streamlined student experience, and much more efficient learning process for students.

In some cases, bandwidth can be a concern for students as well.  Downloading and viewing wrong documents, or waiting for them to download can add up, 

I'd be happy to volunteer to do this grunt work, if nobody in house wants to or has the time to do so.

**Comment by SherylHohman** [comment]
typo: should be: C4.L3.P4

Core 4:       React Native
Lesson 3:  Styling and Layout
Page 4:      Layout in React Native

url:  
https://classroom.udacity.com/nanodegrees/nd019/parts/580105de-1f39-4975-866d-4f430f1aef1d/modules/be422d8e-8927-496d-b203-1868289e90c5/lessons/0d761c28-fb21-432e-a822-f9495ec1b64b/concepts/7e4227ed-4b7b-45bb-8cb3-bb8fe44a65ed#

**Comment by veronikabenkeser** [comment]
Hi Sheryl, thank you so much for your thoughtful and detailed feedback. We are always striving to improve our students' learning experience, so I'll be passing your feedback along to the team. I appreciate you taking the time to let us know what works well and what can be improved about the program!
