### ISSUE TITLE
C2.L4.P1 Introduction video erroneously describes componentWillUnmount()

### ISSUE THREAD

**Issue by nehal96** [udacity/reactnd-issues#284]
In React Fundamentals > Lifecycle Events > Introduction:

In the Introduction video, beginning 1:10, Tyler (and the text section below the video) describes `componentWillUnmount()` as "...invoked immediately before the component is **removed from** the DOM", but the animation text on the side says "invoked immediately before the component is **inserted into** the DOM".

#### Screenshot 👇 

<img width="834" alt="screen shot" src="https://user-images.githubusercontent.com/18629600/38473785-32659432-3b4a-11e8-9971-c2496e2e932c.png">

**Comment by veronikabenkeser** [comment]
Hi @nehal96, Thank you for flagging this issue. We're currently working on a fix.
