### ISSUE TITLE
Lesson 2.2 Summary Does Not Flow

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#29]
Under Rendering UI With React: we have: "You will learn how React creates and renders elements, convert manual element creation to JSX, use ....". The subject of 'convert', 'use' and 'get' is not 'React', rather, it is 'you'. Suggestion: "You will learn how React creates and renders elements. You will convert manual element creation to JSX, use ...".

**Comment by zhangtreefish** [comment]
The link is here: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf

**Comment by forbiddenvoid** [comment]
@richardkalehoff: This is the lesson summary.

**Comment by kellim** [comment]
@zhangtreefish that link doesn't work and I didn't see that sentence on Lesson 2.2

**Comment by zhangtreefish** [comment]
![issue29.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed683e7b5e44130052ea0a/125516c66e82c728ace21e0d46e187893687d1f0cda5fd53b652fa912a5265296b51fa7f28d5e629bd4622075d594cac410e584df9fb8c2fafa42062c80d55b98e30063e937f03a6aa811db500be29834b8cb7b88b4ac2ee3e37aa.jpg)

**Comment by hbkwong** [comment]
Updated! I just split up the clauses per Zhang's suggestion. Here's the new text:

"You'll learn how React creates and renders elements. You'll also convert manual element creation to JSX, use create-react-app to scaffold projects, and get a brief intro to Components."

Thanks for catching that!
