### ISSUE TITLE
C2.L3.S1 Inconsistent git repo reactnd-contacts-complete

### ISSUE THREAD

**Issue by armujahid** [udacity/reactnd-issues#295]
we were asked to clone `starter-files-added` branch of https://github.com/udacity/reactnd-contacts-complete

Problem is all commits from C2.L3.S2 ownwards are refering to a completely different repo https://github.com/udacity/reactnd-contacts-app

This is very confusing. We should use just one git repo `reactnd-contacts-app`.

Reference to `reactnd-contacts-complete` repo should be removed in my opinion and `starter-files-added` should exist in `reactnd-contacts-app`

**Comment by armujahid** [comment]
Also note that master branch of `reactnd-contacts-complete` doesn't work properly. See
https://github.com/udacity/reactnd-contacts-complete/issues/6

**Comment by veronikabenkeser** [comment]
Hi @armujahid, thank you for flagging this! The issue has been fixed.
