### ISSUE TITLE
Typo/Grammar Issue in Lesson1 #5 - "return" should be "returned"

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#3]
Under the Array's .map heading, this sounds like "return" should be "returned": ".map() returns a new array with the values that are return from the arrow function:"

**Comment by forbiddenvoid** [comment]
Please add a link to this page. Thanks!

**Comment by richardkalehoff** [comment]
Fixed!

**Comment by richardkalehoff** [comment]
Fixed!
