### ISSUE TITLE
Workspace Glitch

### ISSUE THREAD

**Issue by nightowl2121** [udacity/reactnd-issues#301]
Whenever I try to add a Route component to my project, my workspace glitches out in such a way that it wont let me scroll properly, and some of the code at the bottom is deleted and replaced with a bunch of random tags (once, it was replaced with a few hundred <div> tags, and another time with a few hundred <e> tags) Luckily, my project was in the beginning stages and not much was lost

**Comment by nightowl2121** [comment]
That is supposed to say "once, it was replaced with a few hundred 'div' tags, and another time with a few hundred 'e' tags)"

**Comment by veronikabenkeser** [comment]
Hi @nightowl2121, that's really odd! Could you please send us an email (https://www.udacity.com/contact) so we could forward this issue to the appropriate team?
