### ISSUE TITLE
C2.L3 Typo wrong about applyMiddleware()

### ISSUE THREAD

**Issue by erwanriou** [udacity/reactnd-issues#303]
In the Redux Middleware lesson (lesson 3), in the second part, in the middle of the page, its wrote:

Note the spread operator on the middlewares parameter. This means that we can pass in as many different middleware as we want! Middleware is called in the order in which they were provided to _appleMiddleware()._

Somehow, i do think by appleMiddleware() it means applyMiddleware() right?

**Comment by veronikabenkeser** [comment]
Thank you for flagging this! Fixed.
