### ISSUE TITLE
C3 - L7 - S10 Inaccurate references and content

### ISSUE THREAD

**Issue by gakf38** [udacity/reactnd-issues#305]
The content at the beginning of this section seems misplaced as it states "In the last video, we saw that the Dashboard Component passed an id property to the Tweet Component" when, in fact, this step was not done in a previous video. Instead the previous video mentioned a few different times that the Tweet component would be handled in the next section. It is easy enough to make sense of this content after watching videos later in the section but it is still confusing to see references to steps that were never detailed in previous videos. I think it would be beneficial for students if this content was revised to better line up with the content of the previous section/videos.

**Comment by veronikabenkeser** [comment]
Thank you for flagging this. Fixed!
