### ISSUE TITLE
C2.L3.V1 Subtitles typo: GFX -> JSX

### ISSUE THREAD

**Issue by brunogarcia** [udacity/reactnd-issues#306]

**Comment by brunogarcia** [comment]
On 0.39 seconds of first video

**Comment by brunogarcia** [comment]
Also on 0:01 seconds on the same video

**Comment by veronikabenkeser** [comment]
@brunogarcia, Could you please provide a link to the video?

**Comment by brunogarcia** [comment]
@veronikabenkeser 
The video link
[https://www.youtube.com/watch?time_continue=3&v=x1fp0wLBI5w](https://www.youtube.com/watch?time_continue=3&v=x1fp0wLBI5w)
