### ISSUE TITLE
ud304-africa lesson 12 unit 16

### ISSUE THREAD

**Issue by ReneeMoodie** [udacity/reactnd-issues#307]
JavaScript course... When you do the quiz, no matter what you answer, you get this answer: "Read each choice carefully. "null" is a string that will be truthy. The value of null on its own would be falsy. The falsy values in JavaScript are listed below:"

**Comment by veronikabenkeser** [comment]
@reneemoodie, could you please provide a link to the quiz?

**Comment by veronikabenkeser** [comment]
Hi Renee,
I checked the quiz, and it's working correctly. Please keep in mind that you can select multiple answers.
