### ISSUE TITLE
Nits: Typos and Bad Links in React Fundamentals

### ISSUE THREAD

**Issue by shawtydubs** [udacity/reactnd-issues#309]
Two small things in React Fundamentals, Module 2, Step 3 (Create React App)
1. Under the MacOS instructions for installing yarn, I believe the last step should be `yarn --version`
2. The Webpack link under "Scaffolding Your React App" links to `create-react-app` on GitHub, instead of the Webpack repo

**Comment by veronikabenkeser** [comment]
Thank you! Fixed.
