### ISSUE TITLE
Lesson 3.2 - Question 1 - update headers

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#31]
"Header 1" and "Header 2" made this question confusing, and I think they may be placeholders for more descriptive headers?

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/6bc1e32e-089d-43ec-aef4-f83b9f7d37cc

**Comment by hbkwong** [comment]
All good to go! I labeled them "concept" and "item", respectively.

**Comment by hbkwong** [comment]
I also updated the modal text for (in)correct responses
