### ISSUE TITLE
C4.L4.P4 Quiz 2 Duplicate drag and drop options

### ISSUE THREAD

**Issue by armujahid** [udacity/reactnd-issues#310]
Quiz is showing duplicate options for each tab navigator.
![image](https://user-images.githubusercontent.com/3725386/40888940-311aff36-6778-11e8-9a3d-1f17390b1c3e.png)

**Comment by veronikabenkeser** [comment]
Hi @armujahid, it's actually not a bug since it was possible that two of the descriptions described the same navigator.
