### ISSUE TITLE
Unable to access apply jobs of android nanodegree

### ISSUE THREAD

**Issue by aman-alam11** [udacity/reactnd-issues#311]
The progress says NaN% complete. There is also an alert on the bottom of page which says "Cannot read property 'title' of undefined"

**Comment by veronikabenkeser** [comment]
@aman-alam11. It looks like this issue is on the wrong Waffle board. Could you please repost this for AndoidND?

**Comment by aman-alam11** [comment]
The udacity Website redirected me to this page. I thought that maybe the website is in react and that is why it is redirecting me here and thus I posted here.
