### ISSUE TITLE
C4.L1.P3 Android Studio Emulator instructions need clearing up for Android Studio 3.1

### ISSUE THREAD

**Issue by nehal96** [udacity/reactnd-issues#315]
This is the current instruction for setting up the Android Studio Emulator (enabling ADB integration):
<img width="815" alt="screen shot 2018-07-13 at 2 09 14 am" src="https://user-images.githubusercontent.com/18629600/42683317-d349a752-8641-11e8-9fde-d99021039ce2.png">

However, Android Studio 3.1.3 does not have the same dropdown setup:
<img width="707" alt="screen shot 2018-07-13 at 2 11 54 am" src="https://user-images.githubusercontent.com/18629600/42683425-27fe9d5c-8642-11e8-8825-db506feb3b56.png">

I looked it up on StackOverflow, but [there's no conclusive answer](https://stackoverflow.com/questions/47904505/android-studio-3-1-does-not-showing-android-option-under-tools-menu). Also, the [Android Studio docs says it's included in the Android SDK Platform-Tools package](https://developer.android.com/studio/command-line/adb#top_of_page), but I'm not sure if that means that it's already setup or not.

Either way, just thought I'd bring it up so you'll can resolve it/update the instructions. 😺

**Comment by veronikabenkeser** [comment]
Thank you! The instructions have been updated.
