### ISSUE TITLE
Quiz Question: React Native L4 S2

### ISSUE THREAD

**Issue by gakf38** [udacity/reactnd-issues#317]
The quiz question in section 2 of lesson 4 (Navigation) of the React Native lecture set seems to have incorrect answers. It currently only accepts the second and fourth answer as a correct answer but I also believe the first answer "createBottomTabNavigator is provided by React Native" should also be true.

**Comment by veronikabenkeser** [comment]
That wouldn't be once of the answers because it's coming from React Navigation.
