### ISSUE TITLE
Lesson 3.2 Question 2 & 3 - light radio buttons

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#32]
The radio buttons to select an answer are so light in Chrome on Mac, I didn't see them at first. 

Using Version 58.0.3029.110 (64-bit) on OSX El Capitan.

**Comment by kellim** [comment]
![light-radio-buttons.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed7ef885a3c51300a05cec/125516c66e82c728ace21e0d46e49d9d2b96cebb8eedb64ce95fe5803d4929606b48e13b628ae92dbc56395b4d5a47a849580a15aead807da4b03e708a0a0ce4d46f5a70cf2f0dbefad341eb5ee779c11ac7a4b6984fc2e23c21ee838b4b3f16061f88f95427ed.png)

link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/6bc1e32e-089d-43ec-aef4-f83b9f7d37cc

**Comment by forbiddenvoid** [comment]
I'm not sure there's anything we can do about this issue. They look fine in all of the browser/OS combinations I looked at.
