### ISSUE TITLE
Lesson 3.2 - localhost:3000 instructions needed

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#33]
Starting with the second video in this lesson, the instructor shows the webpage output by going to localhost:3000 but it was not explained you need to run `npm start` first.

**Comment by kellim** [comment]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/6bc1e32e-089d-43ec-aef4-f83b9f7d37cc#

**Comment by hbkwong** [comment]
Good catch! It was actually mentioned in the previous Lesson, but all the way back in 2.3. Would a quick reminder/set of instructions be a good idea here? @richardkalehoff

**Comment by richardkalehoff** [comment]
Thanks for the helpful feedback! I've added a section on reminding students to verify that their apps are running (the Contacts app and the backend server).
