### ISSUE TITLE
Lesson 3.2 4th video avatar not showing

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#34]
When I follow along with the fourth and last video in lesson 3 part 2, it has you add an avatar and it does not show up when I follow along. 

Link:  https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/6bc1e32e-089d-43ec-aef4-f83b9f7d37cc#

**Comment by kellim** [comment]
![no-avatars.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed7ef885a3c51300a05cec/125516c66e82c728ace21e0d46e69bd7229482bd8efbac01e81fe086264c22703d46f96925dcb770ef477a030b5618ae475a5f44aafe802ea4b33879984019af80330b2b9b645bf9fa9015ad03bc2a8a4b8cbeb88e4ac4ed3820e08c9d02.png)

**Comment by forbiddenvoid** [comment]
The backend service needs to be running for this to work properly.

**Comment by kellim** [comment]
Got it, thanks. It would be a good place to have a reminder that you have to have the backend service running and a link to the lesson where you configure it would be helpful since at least 2 of us beta testers missed it the first time.

**Comment by kellim** [comment]
Well, you do set up the backend server in the prior lesson so maybe most people will be ok with this part. However, that lesson says once you have done this part you can forget about it, but actually you can't because you have to start the server each time you want to run the project.

**Comment by karlud** [comment]
I'll add a reminder that if the images don't show, to check that the server is started.
