### ISSUE TITLE
Lesson 3.5 - recap empty

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#35]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/6e30b216-4065-4c7d-b50b-914dbdf15ec8#

There's a recap heading "Using setState Recap" but there's nothing under it.

**Comment by forbiddenvoid** [comment]
This is already fixed.
