### ISSUE TITLE
Object Restructuring Link not working

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#36]
The link is inside  Core Curriculum/ Section2/Lesson3/segment 7. When I click on the link, it takes me to page https://classroom.udacity.com/me with 'You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?' reminder at the page top.

**Comment by zhangtreefish** [comment]
Sorry, I meant to say 'Object Destructuring'.

**Comment by asparr** [comment]
@zhangtreefish this link is inside the official React Nanodegree rather than the beta version, which is why you cannot access the link.
