### ISSUE TITLE
Typo/Grammar issue in Lesson1 #5 - extra "the"

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#4]
Under the Array's .map heading, this sentence would sound better if you remove the second word, "the": "So the nameLengths will be a new array [7, 4, 5]."

**Comment by forbiddenvoid** [comment]
Please add a link to the page. Thanks!

**Comment by richardkalehoff** [comment]
Fixed!

**Comment by richardkalehoff** [comment]
Fixed!
