### ISSUE TITLE
<angle brackets> have a special meaning!

### ISSUE THREAD

**Issue by karlud** [udacity/reactnd-issues#40]
https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd

In the ".map() Quiz" section, there is an example that uses <angle brackets> to express a template. I wonder if these can be confused with their use in HTML.

**Comment by hbkwong** [comment]
Has there been a lot of student response to this one? It seems relatively clear what quiz asks for ("25 by Adele sold 1731000 copies"), but I do agree that these sort of look like React components. Do you think (parentheses) would be a more viable option? @karlud
