### ISSUE TITLE
Missing semicolon -> Falcon poops

### ISSUE THREAD

**Issue by karlud** [udacity/reactnd-issues#41]
https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd#

In the map quiz, adding this code (with no semicolon on the end) causes a Falcon crash:

const albumSalesStrings = musicData.map(blah =>   blah.name + " by " + blah.artist + " sold " + blah.sales + " copies")

**Comment by richardkalehoff** [comment]
Thanks, Karl! I've updated the quizzes to handle this.
