### ISSUE TITLE
You can't try React examples in your browser console

### ISSUE THREAD

**Issue by karlud** [udacity/reactnd-issues#42]
https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/d9831309-352a-4e04-83f3-ac3e4e8cac76

On this page, there are a bunch of code examples that I, as a JS newbie, was tempted to try out in my browser console. Only, of course, my browser doesn't know React and so they all just errored out.

It would be nice to have a warning near the top, something like:

> React is an extension of JavaScript, but it isn't built into your browser. So you can't test out React code samples in your browser console the way you would if you were learning JavaScript. In the next lesson [or whenever] we'll see how to install and use a React environment. Then you will be able to try out example code.

**Comment by zhangtreefish** [comment]
Will it be helpful that we remind students that if they want, they can try these code at e.g. CodePen ?

**Comment by hbkwong** [comment]
Great! I've since updated the intro text on this page to reflect that. Since the theme of this section is "watch first," I think it's okay to hold off on CodePen for now. We install the React environment in the very next section.

Thank you for your suggestions everyone! Much appreciated 👍
