### ISSUE TITLE
"Create React App" video doesn't show same code as I got

### ISSUE THREAD

**Issue by karlud** [udacity/reactnd-issues#44]
https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/2732ebd0-5868-4c37-ad72-891a367c368f

The third video on this page shows sample code in src/index.js, but it isn't the same as create-react-app gave me; notably, the code in the video doesn't have registerServiceWorker(); at the end.

**Comment by richardkalehoff** [comment]
The code that Michael shows in the recording is from an earlier version of Create React App. The newer version of the package now includes the `registerServiceWorker();` code. This shouldn't cause a problem with the code or progress through the course. But I'll add a notice about it!
