### ISSUE TITLE
Lesson 3, 2 "Pass Data with props" video confusion

### ISSUE THREAD

**Issue by nagamohanm** [udacity/reactnd-issues#45]
same video shown twice. Can we move to next part of the lesson or is it supposed to be a different video?

**Comment by karlud** [comment]
Confirmed, this looks like the same video twice.

https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/6bc1e32e-089d-43ec-aef4-f83b9f7d37cc

**Comment by hbkwong** [comment]
Removed! Thank you for the catch. The video was indeed a duplicate! No other video was meant to be in its place.
