### ISSUE TITLE
3.1 Links to github commits — what is student meant to do with them?

### ISSUE THREAD

**Issue by karlud** [udacity/reactnd-issues#46]
https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/38cbfc18-d355-4297-b45b-db449cb92425

This page seems to ask the student to follow along with a bunch of github commits. But there aren't specific instructions about what to do with the commits, especially the ones that are just a commit rather than a branch.

**Comment by zhangtreefish** [comment]
Will it be helpful to remind students to pay attention to the file paths in the commit, and modify those files accordingly?

**Comment by hbkwong** [comment]
Closing out this older Issue. Thank you Karl and Zhang for the clarifications! The updates have since been made 👍
