### ISSUE TITLE
3.1 node? npm?? yarn???

### ISSUE THREAD

**Issue by karlud** [udacity/reactnd-issues#47]
https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/38cbfc18-d355-4297-b45b-db449cb92425

"The Backend Server" has us start the server with node now, rather than yarn or npm?

Also: "Once you've started the project, you can forget about it."

I think it means once you've started the _server_.

**Comment by hbkwong** [comment]
Great catch. Changed that "project" reference to "server" to avoid any misconceptions. @richardkalehoff Any intended distinction on using `node`?

**Comment by hbkwong** [comment]
Closing this for now! I haven't seen too much chatter in student Slack, but if it does come up, I'll be sure to make the appropriate updates. Thanks again Karl!
