### ISSUE TITLE
Extracurricular locked

### ISSUE THREAD

**Issue by andy1li** [udacity/reactnd-issues#48]
I'm wondering whether there are any particular reasons the ES6, Async JS, and Git parts are locked in the extracurricular region?

**Comment by asparr** [comment]
Ah, they shouldn't be. I will fix this. Thanks for letting me know!

**Comment by asparr** [comment]
This should be resolved now @andy1li

**Comment by andy1li** [comment]
Thanks, Amanda @asparr! All extracurricular parts are unlocked now~
