### ISSUE TITLE
Lesson 1 #5 - Typo/Grammar issue under filter() Method

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#5]
Under Array's .filter() Method, the sentence  "So shortNames will is the new array ['Ryan']." does not sound right - it sounds like it should say "will be" instead of "will is".

**Comment by ghoshabhi** [comment]
:thumbsup: Was about to post this!

**Comment by forbiddenvoid** [comment]
Please add a link to this page. Thanks!

**Comment by ghoshabhi** [comment]
https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/1342b34f-f9f4-4ceb-96e7-6ef0680a26bd

**Comment by richardkalehoff** [comment]
Nice catch - fixed!
