### ISSUE TITLE
broken link - lesson 3.7

### ISSUE THREAD

**Issue by alowie** [udacity/reactnd-issues#51]
In React Lesson 3.7 Controlled Components, the [object destructuring](https://classroom.udacity.com/nanodegrees/nd019/parts/84e6a9ef-f841-44f3-b4cf-f3602402d031/modules/9c5b7af0-0943-4d6e-b672-520440885aba/lessons/42383e89-ac6a-491a-b7d0-198851287bbe/concepts/7c7be588-31e9-4c62-9dad-ecf23f943b19) link is broken.

**Comment by hbkwong** [comment]
Thank you! I've since updated the link for MDN documentation. :)
