### ISSUE TITLE
Update reactnd-project-myreads-starter Readme

### ISSUE THREAD

**Issue by JWebCoder** [udacity/reactnd-issues#56]
The get function from the BooksAPI.js is missing from the Readme, this might lead to people missing the existence of this function.

**Comment by breakpoint25** [comment]
I finished the MyReads project without needing the get function. In what capacity is that function needed?

**Comment by hbkwong** [comment]
Hey JWebCoder, if you're still running into trouble, feel free to check out Live Help or shoot me a Slack directly. This applies to MyReads or anything else React-related. Let's get any roadblocks out of your way.

Enjoy the rest of your week bud!
