### ISSUE TITLE
Controlled comp quiz 3

### ISSUE THREAD

**Issue by andy1li** [udacity/reactnd-issues#57]
Quiz 3:
"Form element receives value from a prop" is judged correct. However, shouldn't it be from the state?

https://classroom.udacity.com/nanodegrees/nd019/parts/331aa737-9e87-42e2-8348-f97d51424b1a/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/fc3f11d3-8779-4d8a-8a23-1cd782f8ddf3#

**Comment by hbkwong** [comment]
Hey Andy! Great question. A form input element's `value` prop (i.e., the initial default/initial value of the input field) can be a property of the component's state. Check out the following example from the React docs:

`<input type="text" value={this.state.value} onChange={this.handleChange} />`

We access the `value` property from the state and interpolate that for the `value` attribute (or, prop) for this element.

Feel free to reach out on Slack if you get stuck! Thanks for checking in :)

**Comment by andy1li** [comment]
Hey Andrew @hbkwong ! Thanks for the prompt answer, which helps me understand that input's value is **technically** from "its" own value prop. 

However, the 2nd answer is set up rather confusingly in the context of the "Controlled component" when the value **ultimately** is controlled by its parent's state. The wording "via a prop" could very easily be interpreted as "a prop of its parent's **props** variable".

And when the 2nd answer was not ticked, the try-again prompt would be "Recall that with Controlled Components, the value of your form elements is tied directly to the component's state.", which could further nudge the reader into the "a prop of its parent's props variable" interpretation.

**Comment by RaghavMangrola** [comment]
I agree, this was incredibly confusing.

**Comment by hbkwong** [comment]
I can definitely see how that confusion could come up. While talking about the `value` prop, we definitely want to be clear that it's an attribute, rather than a React prop. I've since made the change, so we should be good to go on that particular answer choice. Thanks for the feedback everyone!
