### ISSUE TITLE
Lesson 5.7 - Next page automatically loads too soon

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#59]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/3a472639-ed92-4293-897f-ff8b698030b2/concepts/f1e32c27-362a-402a-962f-ca74ff4704bb

It doesn't give you enough time after watching the video to read the text under it and copy the links before automatically going to the next page.

**Comment by hbkwong** [comment]
Hey Kelli, just wanted to check in: did the page successfully render the Stay Here and Play Next buttons right after the video for you?

**Comment by kellim** [comment]
Yes, it does show the buttons, however I don't think it should auto play when there is a paragraph of text beneath a video even if it does have a stay here button. When the video is over, I just start reading the text below without looking for or clicking any buttons (or noticing how many seconds I have to read it before it goes to the next one) and think that others might do the same. I suppose in the scheme of things it is not a huge deal, just a minor annoyance to have to go back to a previous video when it auto plays the next one.

**Comment by asparr** [comment]
Hi @kellim, I filed a ticket with our product design team. This isn't something we can fix immediately on the React Nanodegree team, though I want you to know we're tracking with an internal ticket filed here about this autoplay behavior. Thanks!
