### ISSUE TITLE
Is the forum link needed?

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#60]
All the lessons have links to the forum in them, but there is no React forum which might cause some confusion. 

Example page with the forum link (though I think it's in all of them) https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/e993fa14-8768-4c09-a9df-de2e454ff1cf

**Comment by kellim** [comment]
It looks like the forum link isn't on all the lesson pages, but some of them, especially intros and summaries.

**Comment by hbkwong** [comment]
Hey Kelli! Nice catch -- it does seem like a couple of old forum links still exist (they should be Slack). I'll see what's going on and make sure they're all updated. Thanks!

**Comment by hbkwong** [comment]
All good to go! Have a great Fourth of July, Kelli :]
