### ISSUE TITLE
ES6 extracurricular course

### ISSUE THREAD

**Issue by JWebCoder** [udacity/reactnd-issues#61]
i can’t complete the es6 course, from the extracurricular courses. i've got to the project part, but i can't see the specifications.

**Comment by hbkwong** [comment]
Reassignment of a `const`-declared variable should absolutely give a TypeError. I've since filed a JIRA ticket to to make sure we update this. Thanks JWebCoder!

**Comment by richardkalehoff** [comment]
Thanks for letting us know about this! There shouldn't have been a project associated with this course. It's since been removed. :-)
