### ISSUE TITLE
Search api returning books with a shelf already

### ISSUE THREAD

**Issue by merrettr** [udacity/reactnd-issues#62]
Even when no books are returned from the /books endpoint, certain searches will return with some books that have a shelf value other than 'none'.

Steps to reproduce:
-  Update all books for user to none so that only an empty array is returned from /books
- On the search endpoint send the payload { "query": "i", "maxResults": 50 }
- Note that if you change maxResults to anything other than 50 the issue doesn't occur. 
- Not all queries will produce this, so far "i" and "react" have been found to cause this issue

**Comment by abumalick** [comment]
You have your answer there: https://github.com/udacity/reactnd-issues/issues/78

**Comment by hbkwong** [comment]
Thanks abumalick. Closing out this old issue. merrettr, if you run into any further issues with the project, feel free to Slack me directly! Let's clear out any blockers together
