### ISSUE TITLE
BooksAPI.search() returning attribute shelf: "none" for all books

### ISSUE THREAD

**Issue by adai183** [udacity/reactnd-issues#64]
There is something confusing about the books Api. It is probably a bug.

`BooksAPI.search()` always returns `shelf: "none" ` even for books that have a shelf assigned.

`BooksAPI.getAll()` works as expected and returns a response with the corresponding bookshelfs.

**Comment by abumalick** [comment]
You have your answer there: https://github.com/udacity/reactnd-issues/issues/78

**Comment by hbkwong** [comment]
Closing out this old issue. If you still run into any roadblocks, feel free to send me a message directly on Slack! Let's clear them out for you (especially before the upcoming due date for the project) 👍
