### ISSUE TITLE
Extracurricular - ES6 - Lesson 3 - Wrong results

### ISSUE THREAD

**Issue by miguelangel** [udacity/reactnd-issues#65]

**Comment by miguelangel** [comment]
Hi!

Extracurricular - ES6 - Lesson 3 -  Iteration and Iterable protocols

The following code passes the tests, but I think it is incorrect at the following sentence:

    if (count + 1 >= properties.length) {

The right version should be:
    if (count + 1 > properties.length) {

(if I leave the 'wrong version', it does not iterate through all the items)

/*
 * Programming Quiz: Make An Iterable Object
 *
 * Turn the `james` object into an iterable object.
 *
 * Each call to iterator.next should log out an object with the following info:
 *     - key: the key from the `james` object
 *     - value: the value of the key from the `james` object
 *     - done: true or false if there are more keys/values
 *
 * For clarification, look at the example console.logs at the bottom of the code.
 */

// MMZ: Based on https://goo.gl/6GDs62
//      Thanks and ♥ to stackoverflow guys!

const james = {
    name: 'James',
    height: `5'10"`,
    weight: 185
};

// define the Iterator for the options object
james[Symbol.iterator] = function() {
  // get the properties of the object
  let properties = Object.keys(this);
  let count = 0;
  // set to true when the loop is done
  isDone = false;

  // define the next method, need for iterator
  let next = () => {
    // control on last property reach
    if (count + 1 >= properties.length) {
      isDone = true;
    }

    return {
      value: this[properties[count]],
      key: properties[count++],
      done: isDone
    }
  }
  
  // return the next method used to iterate
  return { next }
}

let iterator = james[Symbol.iterator]();

//console.log(iterator.next().value); // 'James'
//console.log(iterator.next().value); // `5'10`
//console.log(iterator.next().value); // 185

**Comment by hbkwong** [comment]
Thanks for checking in, miguelangel! I created a JIRA ticket to make sure this is fixed in a future release. Have a great week!
