### ISSUE TITLE
Style Guide out of date

### ISSUE THREAD

**Issue by forbiddenvoid** [udacity/reactnd-issues#66]
The Udacity front end style guide recommends against using const because of lack of browser support. This is no longer the case, so this needs to be updated.

**Comment by forbiddenvoid** [comment]
http://udacity.github.io/frontend-nanodegree-styleguide/

**Comment by richardkalehoff** [comment]
Updated! [Check out the commit!](https://github.com/udacity/frontend-nanodegree-styleguide/commit/542b0a92ea8f4bf58d796c801a8c4515e9f42e42)
