### ISSUE TITLE
Extracurricular - ES6 - Lesson 3 - Built-ins

### ISSUE THREAD

**Issue by miguelangel** [udacity/reactnd-issues#68]
Hi! 

  I think that there is an incorrect information on the last paragraph of this page:
https://classroom.udacity.com/nanodegrees/nd019/parts/290ec447-6555-41bf-ac39-457220a09aae/modules/9c5b7af0-0943-4d6e-b672-520440885aba/lessons/1b997dce-e2ce-4246-b5ae-d39ca175f887/concepts/a9340848-55d9-490a-8ebd-72da5b111578

It states the following:
__Both methods return true if a key-value pair is successfully added or deleted from the Map and false if unsuccessful.__

That is incorrect according to msd:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set

Set method returns the Map object, not true or false.

Hope it helps!

**Comment by hbkwong** [comment]
This has since been fixed. To close the loop `.set()` returns the `Map` object itself (if successful), while `.delete()`returns a boolean
