### ISSUE TITLE
Lesson 3:5 update state with setState - 2nd video need a end pause

### ISSUE THREAD

**Issue by idisblueflash** [udacity/reactnd-issues#69]
I need a close look on code of this video, but  our video player quit with quick. I have to drag timeline to that location. It's not convenient. 

https://s3.cn-north-1.amazonaws.com.cn/u-vid-hd/d3UNPA863f4.mp4

**Comment by hbkwong** [comment]
idisblueflash, can you please describe the steps to reproduce this error? For convenience, code featured in videos is available via the commit links as well. If you're still running into issues, feel free to send me a Slack! Let's get down to the bottom of this together

**Comment by hbkwong** [comment]
Closing this for now. Please feel free to message me on Slack if something is broken (or if you're still running into roadblocks getting the code)
