### ISSUE TITLE
Broken Link: Lesson 3: Part 1

### ISSUE THREAD

**Issue by ghoshabhi** [udacity/reactnd-issues#7]
The following lesson has a broken link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/38cbfc18-d355-4297-b45b-db449cb92425

https://github.com/ReactTraining/udacity-react-fundamentals/commit/191cbdd010ac04cecb8f9748a9ddd0a9f4af5f13

**Comment by kellim** [comment]
It seems difficult to continue without knowing what's in this link as I'm assuming it gives you instructions on what you need to do to update your create-react-app project.

**Comment by avastamin** [comment]
git clone https://github.com/udacity/reactnd-contacts-server.git is an empty directory

**Comment by karlud** [comment]
Broken link is under the section heading "Our Starter Files".

**Comment by richardkalehoff** [comment]
I've updated the link to point to the correct content.
