### ISSUE TITLE
Link in Unidirectional-dataflow

### ISSUE THREAD

**Issue by drodeur** [udacity/reactnd-issues#71]
The current link of Angular's two-way data binding is :

https://angular.io/guide/template-syntax#!#two-way

But, this isn't a right syntax for an anchor link. The real page you want to go is :

https://angular.io/guide/template-syntax#two-way

**Comment by hbkwong** [comment]
Hey @drodeur, just wanted to close the loop on this one. It's since been fixed. Thanks for the original report!
