### ISSUE TITLE
Lesson 1.5 Hyperlink

### ISSUE THREAD

**Issue by pkayokay** [udacity/reactnd-issues#72]
On Lesson 1 Part 5, the forums hyperlink is linked to the slack, not the forums. Is there a forum specific to React?

**Comment by hbkwong** [comment]
Great question, pkayokay! For the React Nanodegree Program, we have Slack and Live Help to make sure you have the support you need. Out of curiosity, is there a particular feature you're looking for in the forums? Definitely want to make sure you're covered! Feel free to shoot me a direct message as well.

**Comment by pkayokay** [comment]
I just wanted to make sure it was linked correctly. Slack and Live help should suffice in support for this Nanodegree!

**Comment by hbkwong** [comment]
No problem! Thanks for looking out. If you do find that another channel of support can be useful, feel free to reach out :]
