### ISSUE TITLE
can't reassign constant variable

### ISSUE THREAD

**Issue by rscharfer** [udacity/reactnd-issues#73]
Extracirricular ES6 : Lesson 3 Built Ins : 16 Weak Maps

The constant 'book1' is reassigned with a new value later on in the example.

**Comment by rscharfer** [comment]
This occurs in both the video and text on the page.

**Comment by hbkwong** [comment]
Hey rscharfer, totally with ya on this one! Reassigning a constant variable should throw a TypeError. I filed a JIRA ticket for our team on this one.

Thanks for reaching out 👍
