### ISSUE TITLE
1.5 .filter() Quiz user is unable to on answer field (Chrome browsers, MacOS Serria)

### ISSUE THREAD

**Issue by Raywilliams01** [udacity/reactnd-issues#74]

**Comment by pkayokay** [comment]
This seems fine to me. Have you tried tried copying/pasting the answer that is hidden on the hover? Just want to make sure this is not just an incorrect answer issue. 😄

**Comment by hbkwong** [comment]
Hey raywilliams01, are you still running into this issue? Do you have any details on how to reproduce this error (also including your version of Chrome, Mac OSX, etc.).

**Comment by hbkwong** [comment]
Closing this for now, but definitely feel free to Slack me if you run into trouble!
