### ISSUE TITLE
BooksAPI.search() returning duplicates

### ISSUE THREAD

**Issue by danhayden** [udacity/reactnd-issues#75]
If you search for `react` with max results set to 20 you get 3 duplicates.

Duplicates for this search are book with ids `47FKDAAAQBAJ`, `_97JDAAAQBAJ`, and `a_asDAAAQBAJ`

**Comment by danhayden** [comment]
duplicates for this search are book with ids `47FKDAAAQBAJ`, `_97JDAAAQBAJ`, and `a_asDAAAQBAJ`

**Comment by cjkoepke** [comment]
I can confirm that this is also happening.

**Comment by abumalick** [comment]
Yes same here

**Comment by claudiokc** [comment]
I have the same problem with the "React" query on the BookAPI

**Comment by hbkwong** [comment]
This is a weird one. For some reason, Google Books decided to list some books (with the same ID) twice, albeit with a different `previewLink`. I removed one instance of each of these three dups in `react.txt`. We're good to go! Thanks for reaching out, everyone
