### ISSUE TITLE
Lesson 3.2 Quiz 1 cannot be answered

### ISSUE THREAD

**Issue by pakaponk** [udacity/reactnd-issues#76]
It seem the drag and drop function is not working

**Comment by hbkwong** [comment]
Hi pakaponk, thanks for checking in. Can you share some details on your environment to reproduce the issue? I'm running Chrome version 59 with OSX Sierra and things seem to be run fine. Let's get down to the bottom of this together!

**Comment by pkayokay** [comment]
This seems to work fine with me as well (Chrome 59 with Sierra). I tried Safari and it also works fine.

**Comment by pakaponk** [comment]
@hbkwong It also works fine for me now after I restarted my computer.

When it still happened, I tried both on Chrome 59 and Safari with OSX Sierra and it didn't work for me.
On Chrome, the browser started 'not responding' immediately after I had dragged and dropped the answer box to the blank field.
On Safari, it just not working

Maybe the problem lies with my computer

**Comment by hbkwong** [comment]
@pakaponk, I just tried out the same quiz in Safari (10.1.1) and things seemed okay too. If you run into further issues in later quizzes (or any part of the classroom, really), let me know.

**Comment by hbkwong** [comment]
Closing this for now. Definitely feel free to Slack me (or open up a new issue) if you see this later on in the course!
