### ISSUE TITLE
Inconsistent BookAPI Behavior

### ISSUE THREAD

**Issue by cjkoepke** [udacity/reactnd-issues#78]

**Comment by cjkoepke** [comment]
When I make a call to the .search(query) method, it returns results of a book that are inconsistent from when I directly query that book via the .get(bookID) method.

For instance: api.search('finance').then(res => console.log(res));

This will return a list of books, the first of which being "Lords of Finance", with the shelf set to "wantToRead".

In comparison: api.get('74XNzF_al3MC').then(res => console.log(res));

This will return the book in question, but this time the shelf property is set to "none". This creates inconsistent behavior between the search page and the main bookshelf page.

**Comment by sobbuh** [comment]
I also ran into this problem

**Comment by ryanwaite28** [comment]
When making a call to the api update method, the book's shelf doesn't update. the shelf parameter is not specified as what it should be. a string? object? array?

**Comment by cjkoepke** [comment]
@ryanwaite28 it should be a string, and it works for me.

**Comment by ryanwaite28** [comment]
It works now, thanks. Also, why did udacity lock each part for different dates? i could of finished this Nanodegree in a week if i was allowed to...

**Comment by mariopeixoto** [comment]
I'm running into the same problem. The data returned from /books and /search are inconsistent.

For example, if I make a request to the /books url with token `anwn67yx`, it will return that book with id `bUybAgAAQBAJ` (Best Android Apps) is on the `read` shelf (check the response [here](https://gist.github.com/mariopeixoto/27930cc387650993a9bfda0b361abae0)). If I make a request to the /search url with the same token, it's returning `none` for the shelf for that same book (response [here](https://gist.github.com/mariopeixoto/49ead1ba66e9dcdfedb6034d6ee2d645))

That is not happening for every book, just a few of them.

**Comment by cjkoepke** [comment]
So I think they're working on fixing this, but for the record it is expected that you solve and reconcile the results of `.search()` to the `.getAll()` method.

**Comment by pakaponk** [comment]
I think they probably going to  leave it that way because they already mentioned in `search`method section at https://github.com/udacity/reactnd-project-myreads-starter that 
this behavior is expected

Noted that the search result is just a **CACHED** search result **for EVERYONE**. If you make the book in your bookshelves consistent with the search result, It is going to not be consist with the others.

Otherwise, they have to cache the search result for each one of us separately which I think is not worth the effort for the class project

**Comment by cjkoepke** [comment]
@pakaponk Thanks for the input, here it is in the doc:

> These books do not know which shelf they are on. They are raw results only. You'll need to make sure that books have the correct state while on the search page.

With that in mind, I'm going to close this issue as I missed that part of information. Thanks!
