### ISSUE TITLE
sentence flow in Redux/Lesson1/segment5: Pure function

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#79]
'For example, a button with an event handler that updates the DOM wouldn’t be great choices for pure functions because the event handler is updating the DOM (i.e., producing a side effect!). ' : I feel the 'choices' should be 'use cases'. or , rather: 'For example, pure functions wouldn’t be great choices for a button with an event handler that updates the DOM   because the event handler is updating the DOM (i.e., producing a side effect!). '

**Comment by hbkwong** [comment]
Hey zhangtreefish, the update has been made. "Use cases" does sound closer to the intended message. Thanks for reaching out on that!
