### ISSUE TITLE
Incomplete Content Lesson 3: Part 4

### ISSUE THREAD

**Issue by ghoshabhi** [udacity/reactnd-issues#8]
[Link](https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/14331e60-a548-4cfb-a326-054545da8927/concepts/c7172108-9c9f-42d7-9f2b-0e42a2f7130b)
<img width="726" alt="screen shot 2017-06-20 at 11 46 32 am" src="https://user-images.githubusercontent.com/19292575/27350118-598f4c06-55ae-11e7-9b83-aa13293212b1.png">

**Comment by hbkwong** [comment]
Updated a few days ago! Moving this card to `Complete`. Thanks for the heads up!
