### ISSUE TITLE
Consistent naming in ".map Quiz" instructions

### ISSUE THREAD

**Issue by josheche** [udacity/reactnd-issues#80]
Very tiny typo, could be left alone since doesn't cause too much confusion.

"Use the provided music data array and the .map() method to create a new array that contains items in the format:

<album> by <artist> sold <sales> copies"

----

<album> should be <album-name> to maintain consistency across instructions just below it stating use of a hyphen for albums with spaces as <album-name>.

**Comment by josheche** [comment]
It can also be "name" since that's the data from the array anyway.

**Comment by hbkwong** [comment]
Hey joseche, I haven't seen too much confusion with the wording of the quiz, but I'm totally with ya -- let's change `artist` to `name`for consistency (since that was a key in the original object). Thanks for reaching out on this one!
