### ISSUE TITLE
redux/lesson2/segment3 reducer quiz

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#81]
With ```const appReducer =( action, state=[]) => {
    switch(action.type){
        case 'DELETE_FLAVOR':
           return state.filter(f => f !== action.flavor )
        default:
            return state
    }
}``` I could get the correct output for ```console.log(appReducer({ type: 'DELETE_FLAVOR', flavor: 'vanilla' }, ['vanilla', 'cayenne']))```. However, it did not pass the grader.

**Comment by zhangtreefish** [comment]
![redux_lesson2_seg_3_reducerQuiz.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed683e7b5e44130052ea0a/125516c66e82c728ace21e0d46fa919e369abca58afaac4caa0fcf872c4118201616a62f6586e63a8e57721b4d435cec03070511afbd9b21b4b33574825c5ebc83395622c43b13acb8d418b604b8258f4697aaaec81d9ebc6278bec1da0d2c14171b88f55c30a0984cc85ef643e74d53ac017b.jpg)
![redux_lesson2_seg_3_reducerQuizTryAgain.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed683e7b5e44130052ea0a/125516c66e82c728ace21e0d46fa919e369abca58afaac4caa0fcf872c4118201616a62f6586e63a8e57721b3b1d07dd1609061aeee59b6be4e96625d91819e7c3685670ce3d44fdead616e903bc228b4fd3b1b58f4ec5ec3437fb99cd1e604a5a45d0b50877b29359cb59fc4ae44d54a3133063ef74307d468653.jpg)

**Comment by hbkwong** [comment]
Hey zhangtreefish, thanks for documenting this one! Really solid point.

I just made a quick update to the prompt (feel free to reset the editor if it doesn't show up). The problem is that the initial state should be an array of flavor objects (with "flavor" and "count" keys), rather than an array of individual strings representing flavors. Let me know how it goes!

**Comment by zhangtreefish** [comment]
using the new state(note the 'vanilla' in action and 'Vanilla' in initialState in the quiz editor): 
![redux_lesson2_seg_3_reducerquizv2](https://user-images.githubusercontent.com/10746052/28900640-40a95354-77b8-11e7-914d-fc456f007e2a.jpg)

![redux_lesson2_seg_3_reducerquizv2tryagain](https://user-images.githubusercontent.com/10746052/28900642-4b42f360-77b8-11e7-9bbd-cab7e709594e.jpg)

**Comment by zhangtreefish** [comment]
@hbkwong ^^^
