### ISSUE TITLE
redux/lesson3/segment4 curry: order of curry parts

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#83]
First we have:
connect(MyComponent)(mapStateToProps, mapDispatchToProps)
connect(User)(mapStateToProps)
connect(User)()
connect(User)(null, mapDispatchToProps)

Then in Quiz 3 and videos we have ```export default connect( mapStateToProps, mapDispatchToProps )(ContactForm); ``` and likes. 
I am not sure if both version works and the lesson means to introduce both to students, or the first version where Components come first is not right.

**Comment by zhangtreefish** [comment]
Since currying is like a pipe-kind of one-directional flow, I am guessing that components should be on the right of those maps since they RECEIVE those props.

**Comment by hbkwong** [comment]
Fixed! To be honest, I've only ever seen it as how you described (presentational components on the right), @zhangtreefish. If you run into this in other examples, let me know! Videos and the project itself remain unchanged. Thank you as always for helping out!
