### ISSUE TITLE
redux/lesson2/segment3: #81,Still have issue

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#84]
Please see comment to #81

**Comment by hbkwong** [comment]
Hey zhangtreefish, there's a distinction between the initial state's flavor values and the flavor value from action payload (letter case). If it's still giving you an error let me know!

**Comment by hbkwong** [comment]
Hey zhangtreefish, thanks for staying on this one! Much appreciated. 

I changed things up from your feedback. The original solution had a distinction between lower case and upper case flavor strings (i.e., the action payload's flavor was "vanilla", while the initial state's flavor was "Vanilla"). I updated to tests to remove this. How do things look now?

**Comment by zhangtreefish** [comment]
![redux_lesson2_seg_3_reducerQuizV3TryAgain.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed683e7b5e44130052ea0a/125516c66e82c728ace21e0d46fa919e369abca58afaac4caa0fcf872c4118201616a62f6586e63a8e57721b395c2aee08290815a5a79b37b4f67e2fd00958a9c3674d71cf3919acedd34deb08ec228d4d85b6ea8d45c5ea3821ee99935d7c4f5b4cd6a2047ff5db59c24af54aeb4c50a412316be37f347e4494186761.jpg)

**Comment by hbkwong** [comment]
This was the solution I had used:

```js
const appReducer = (state, action) => {
  switch (action.type) {
    case 'DELETE_FLAVOR':
      return state.filter(f => f.flavor !== action.flavor );
    default:
      return state;
  }
};
```

**Comment by zhangtreefish** [comment]
Adding a default value for state, ```const appReducer = (state=[], action) => {``` produced the above error.  Thank you!

**Comment by hbkwong** [comment]
No worries! Thanks for the quick response @zhangtreefish
