### ISSUE TITLE
redux/lesson1/segment6 filter-reduce quiz

### ISSUE THREAD

**Issue by sejas** [udacity/reactnd-issues#85]
Quiz Name: Combining Filter and Reduce Quiz
Lesson 1 , part 6: Array’s .reduce() method

I didn't accepted any of my answers.
It just says : "Your totalAlbumSales array does not match the expected result"

**Comment by hbkwong** [comment]
Hey sejas, thanks for reaching out on this one. Can you post your solution so I can check in on the issue?

**Comment by hbkwong** [comment]
Hey sejas, good catch. The example below mentions "for example, looking at the first album it would be "Adele25" which has a length of 7, so it should be included." I made a quick update just now, so try filtering for a different condition and it should work out. Let me know how it works!

**Comment by sejas** [comment]
Great !!,
Now I passed the Quiz  😀
Thank you !!

**Comment by hbkwong** [comment]
Keep at it! Got your back. Let us know if you run into any other roadblocks 👍
