### ISSUE TITLE
Wrong Video Order-Redux Lesson2-Section2

### ISSUE THREAD

**Issue by jalil** [udacity/reactnd-issues#88]
Tyler is talking about the final project even though we don't know what he is talking about.  Seems like a previous video was skipped.

**Comment by hbkwong** [comment]
Hey jalil, thanks for checking in! I think Tyler's intended message was the final stage of this in-class project. I'm looking to add a couple more details (e.g. screenshots, animations, etc.) soon. In the meantime, feel free to check out the repo, especially the functionality in question, here: https://github.com/udacity/reactnd-udacimeals-complete/blob/master/src/actions/index.js

**Comment by hbkwong** [comment]
If you run into any roadblocks along the way, feel free to open another issue (or find me on Slack).

**Comment by LGLC** [comment]
@hbkwong The same thought occurred to be.  Tyler starts with, 'If you remember back to the final project' and then goes on to say 'there are two different ways we can change the state of our redux store.  The first way is by adding a recipe and the second way is by removing a food item from the calendar.'  At this point, we have no context about what this video even relates to.  I found myself asking, 'Have I missed something?  What recipes?  What food items?  Should I be remembering the project?  Should I know what the app is now and that these are the two ways to change the state?'  The only clue that this related to this section was the text above stating, 'Let's go ahead and begin building the in-class project, Udacimeals!'  I assumed at this point that the recipe and food items must relate to the 'meals' section in the project title and therefore must be to do with the in-class project. 

I think an intro and description of what the in-class project is is what's needed, in the 'Starting the Project' section and just before the video :)

**Comment by LGLC** [comment]
*to me

**Comment by hbkwong** [comment]
Fixed in #110!
