### ISSUE TITLE
Lesson 1.3 Add space to _imperative_code

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#9]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/9a065aa0-91d4-44a3-ad96-8d9b44be4d11/concepts/dad1ab97-c06e-43fa-a29a-827a9518812e 

Under the Imperative Code heading, there's a sentence that says "This is _imperative_code, though." 

I'm not sure if the underscores are intentional around imperative, but it looks like if they are, there should be a space between _imperative_ and code.

**Comment by forbiddenvoid** [comment]
Already fixed!
