### ISSUE TITLE
Contradictory information on where to import Provider

### ISSUE THREAD

**Issue by Mackiovello** [udacity/reactnd-issues#90]
In Redux lesson 3 lesson 2 "Provider"  it says:

> Be sure to also import Provider to the component being rendered into the DOM by ReactDOM (e.g., app.js or root.js):

This is incorrect, at least if we'll trust the video where `Provider` is imported in `index.js`.

**Comment by hbkwong** [comment]
Hey @Mackiovello, thanks for reaching out. I typically prefer to name that component root.js (it contains the Provider which wraps my App component), then have that rendered in my entry file for Webpack. All in all, the name of the file itself isn't a huge deal; it's what's inside the file. Tyler's screencast has it as index.js, but feel free to name it whatever you see fit!
