### ISSUE TITLE
Duplicate text and code

### ISSUE THREAD

**Issue by Mackiovello** [udacity/reactnd-issues#91]
In Redux lesson 3 section 3 "Currying", this section is repeated two times right next to each other:

> Here we have a simple plate function which takes in two arguments,: a vegetable and a fruit.
  ```js
  function plate(vegetables, fruit) {
    return `I ate a plate of ${vegetables} and ${fruit}!`;
  }
  
  plate('corn', 'apples');
  ```

On the second version, there's also an incorrect comma after "arguments".

**Comment by hbkwong** [comment]
Yikes - thanks for checking in on this. That shouldn't have happened. Fixed!
