### ISSUE TITLE
Inconsistent use of parentheses after function names in text

### ISSUE THREAD

**Issue by Mackiovello** [udacity/reactnd-issues#92]
In Redux lesson 3 section 4 "Connect", the `connect` function is written out with parentheses while other functions, like `mapStateToProps`, are not. Even if this is a minor thing, it might be confusing at times. I would rather be consistent and always write the function names without the parentheses, i.e `connect` not `connect()`

**Comment by hbkwong** [comment]
Good catch! It may be a minor thing, but it's a quick fix. Thanks for chiming in on this one Mackiovello!

**Comment by Mackiovello** [comment]
@hbkwong it's still not consistent across the nanodegree. In the middleware part it uses three types of syntax for methods and functions:
* `.functionName()`
* `functionName()`
* `functionName`

**Comment by hbkwong** [comment]
Hey @Mackiovello, just did a quick scrub of those Middleware sections. I'll give it another go through this week, too. If you do find something that needs immediate, feel free to check in too. Hope you're having a great weekend 👍

**Comment by hbkwong** [comment]
Hey @Mackiovello, just did a quick scrub of those Middleware sections. I'll give it all another go through this week, too. If you do find something that needs immediate, feel free to check in too. Hope you're having a great weekend 👍
