### ISSUE TITLE
Iteration & Iterable Protocol Quiz

### ISSUE THREAD

**Issue by evankline** [udacity/reactnd-issues#93]

**Comment by evankline** [comment]
https://classroom.udacity.com/nanodegrees/nd019/parts/290ec447-6555-41bf-ac39-457220a09aae/modules/9c5b7af0-0943-4d6e-b672-520440885aba/lessons/1b997dce-e2ce-4246-b5ae-d39ca175f887/concepts/966cea8f-5583-4d46-80ef-ed4c829c63c7#

This quiz has been a problem for many students on React Live Help and I'm not sure how to create an iterable out of a JS object any other way besides this: https://gist.github.com/evankline/5d236a90cf31cf24e3745e6452221852

But the above doesn't pass the quiz.

**Comment by breakpoint25** [comment]
Here is working example, but I felt the section doesn't really give a good overview to expect someone to create such an example

https://gist.github.com/breakpoint25/b4276956a2f56901947b31aa23d1ffa2

**Comment by hbkwong** [comment]
Thanks for reporting, evankline! I've added this to our JIRA board to update in a future release.
