### ISSUE TITLE
Punctuation

### ISSUE THREAD

**Issue by jenniesyip** [udacity/reactnd-issues#97]
Lesson 1, Part 3. What is Declarative Code? 
- Space missing after `...` --> `Notice that there's just an onClick attribute on the button...we aren't using .addEventListener() to set up event handling with all of the steps involved to set it up.`

Lesson 1, Part 5. React is "Just Javascript"
- Space missing after `...` --> `But React builds on a lot of the techniques of functional programming...techniques that you'll learn as you go through this program. `
- Dash should be a longer — dash --> `React builds on what you already know - JavaScript!`

Lesson 2, Part 3. Create React App
- Period after `though` should be a comma --> `If you want to remove it, though. Feel free!`

Lesson 2, Part 4. Rendering UI with React
- Period goes inside quote --> `You might have heard before that it’s better to “favor composition over inheritance”.`

Lesson 3, Part 1. Intro
- `checkout` should be one word. --> `Or, you can clone this repo and check out the starter-files-added branch to have it all done for you.`

**Comment by asparr** [comment]
Thanks @jenniesyip! Much better now!
