### ISSUE TITLE
ES6 Built-ins - Iteration & Iterable Protocols - Need to add answer to Quiz

### ISSUE THREAD

**Issue by thetreythomas** [udacity/reactnd-issues#98]
On the Quiz at the bottom of the page, this is super difficult. After struggling with it for hours, I gave up.

This is one that for sure needs the answer displayed after several incorrect submissions.

**Comment by hbkwong** [comment]
Referenced [here](https://github.com/udacity/reactnd-issues/issues/93). Closing this one for now, and will be posting a resolution on that page. Thanks for checking in, @thetreythomas
